// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: messages-debug.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Trezor.Net.Contracts.Debug
{

    [ProtoBuf.ProtoContract()]
    public class DebugLinkDecision : ProtoBuf.IExtensible
    {
        private ProtoBuf.IExtension __pbn__extensionData;
        ProtoBuf.IExtension ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [ProtoBuf.ProtoMember(1, Name = @"yes_no")]
        public bool YesNo
        {
            get { return __pbn__YesNo.GetValueOrDefault(); }
            set { __pbn__YesNo = value; }
        }
        public bool ShouldSerializeYesNo() => __pbn__YesNo != null;
        public void ResetYesNo() => __pbn__YesNo = null;
        private bool? __pbn__YesNo;

        [ProtoBuf.ProtoMember(2, Name = @"up_down")]
        public bool UpDown
        {
            get { return __pbn__UpDown.GetValueOrDefault(); }
            set { __pbn__UpDown = value; }
        }
        public bool ShouldSerializeUpDown() => __pbn__UpDown != null;
        public void ResetUpDown() => __pbn__UpDown = null;
        private bool? __pbn__UpDown;

        [ProtoBuf.ProtoMember(3, Name = @"input")]
        [System.ComponentModel.DefaultValue("")]
        public string Input
        {
            get { return __pbn__Input ?? ""; }
            set { __pbn__Input = value; }
        }
        public bool ShouldSerializeInput() => __pbn__Input != null;
        public void ResetInput() => __pbn__Input = null;
        private string __pbn__Input;

    }
}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
