


// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: my.proto

using System.Collections.Generic;
using ProtoBuf;

#pragma warning disable CS1591, CS0612, CS3021

namespace Trezor.Net.Contracts
{

    [ProtoContract]
    public class FileDescriptorSet
    {
        [ProtoMember(1, Name = @"file")]
        public List<FileDescriptorProto> Files { get; } = new List<FileDescriptorProto>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
