// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: messages-management.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Trezor.Net.Contracts.Management
{

    [global::ProtoBuf.ProtoContract()]
    public class Initialize : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"state")]
        public byte[] State
        {
            get { return __pbn__State; }
            set { __pbn__State = value; }
        }
        public bool ShouldSerializeState() => __pbn__State != null;
        public void ResetState() => __pbn__State = null;
        private byte[] __pbn__State;

        [global::ProtoBuf.ProtoMember(2, Name = @"skip_passphrase")]
        public bool SkipPassphrase
        {
            get { return __pbn__SkipPassphrase.GetValueOrDefault(); }
            set { __pbn__SkipPassphrase = value; }
        }
        public bool ShouldSerializeSkipPassphrase() => __pbn__SkipPassphrase != null;
        public void ResetSkipPassphrase() => __pbn__SkipPassphrase = null;
        private bool? __pbn__SkipPassphrase;

    }
}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
