// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: messages-debug.proto
// </auto-generated>

#pragma warning disable
using Trezor.Net.Contracts.Common;

namespace Trezor.Net.Contracts.Debug
{

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkDecision : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"yes_no")]
        public bool YesNo
        {
            get => __pbn__YesNo.GetValueOrDefault();
            set => __pbn__YesNo = value;
        }
        public bool ShouldSerializeYesNo() => __pbn__YesNo != null;
        public void ResetYesNo() => __pbn__YesNo = null;
        private bool? __pbn__YesNo;

        [global::ProtoBuf.ProtoMember(2, Name = @"swipe")]
        [global::System.ComponentModel.DefaultValue(DebugSwipeDirection.Up)]
        public DebugSwipeDirection Swipe
        {
            get => __pbn__Swipe ?? DebugSwipeDirection.Up;
            set => __pbn__Swipe = value;
        }
        public bool ShouldSerializeSwipe() => __pbn__Swipe != null;
        public void ResetSwipe() => __pbn__Swipe = null;
        private DebugSwipeDirection? __pbn__Swipe;

        [global::ProtoBuf.ProtoMember(3, Name = @"input")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Input
        {
            get => __pbn__Input ?? "";
            set => __pbn__Input = value;
        }
        public bool ShouldSerializeInput() => __pbn__Input != null;
        public void ResetInput() => __pbn__Input = null;
        private string __pbn__Input;

        [global::ProtoBuf.ProtoMember(4, Name = @"x")]
        public uint X
        {
            get => __pbn__X.GetValueOrDefault();
            set => __pbn__X = value;
        }
        public bool ShouldSerializeX() => __pbn__X != null;
        public void ResetX() => __pbn__X = null;
        private uint? __pbn__X;

        [global::ProtoBuf.ProtoMember(5, Name = @"y")]
        public uint Y
        {
            get => __pbn__Y.GetValueOrDefault();
            set => __pbn__Y = value;
        }
        public bool ShouldSerializeY() => __pbn__Y != null;
        public void ResetY() => __pbn__Y = null;
        private uint? __pbn__Y;

        [global::ProtoBuf.ProtoMember(6, Name = @"wait")]
        public bool Wait
        {
            get => __pbn__Wait.GetValueOrDefault();
            set => __pbn__Wait = value;
        }
        public bool ShouldSerializeWait() => __pbn__Wait != null;
        public void ResetWait() => __pbn__Wait = null;
        private bool? __pbn__Wait;

        [global::ProtoBuf.ProtoContract()]
        public enum DebugSwipeDirection
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UP")]
            Up = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"DOWN")]
            Down = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"LEFT")]
            Left = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"RIGHT")]
            Right = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkLayout : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"lines")]
        public global::System.Collections.Generic.List<string> Lines { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkReseedRandom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"value")]
        public uint Value
        {
            get => __pbn__Value.GetValueOrDefault();
            set => __pbn__Value = value;
        }
        public bool ShouldSerializeValue() => __pbn__Value != null;
        public void ResetValue() => __pbn__Value = null;
        private uint? __pbn__Value;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkRecordScreen : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target_directory")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TargetDirectory
        {
            get => __pbn__TargetDirectory ?? "";
            set => __pbn__TargetDirectory = value;
        }
        public bool ShouldSerializeTargetDirectory() => __pbn__TargetDirectory != null;
        public void ResetTargetDirectory() => __pbn__TargetDirectory = null;
        private string __pbn__TargetDirectory;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkShowText : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"header_text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string HeaderText
        {
            get => __pbn__HeaderText ?? "";
            set => __pbn__HeaderText = value;
        }
        public bool ShouldSerializeHeaderText() => __pbn__HeaderText != null;
        public void ResetHeaderText() => __pbn__HeaderText = null;
        private string __pbn__HeaderText;

        [global::ProtoBuf.ProtoMember(2, Name = @"body_text")]
        public global::System.Collections.Generic.List<DebugLinkShowTextItem> BodyTexts { get; } = new global::System.Collections.Generic.List<DebugLinkShowTextItem>();

        [global::ProtoBuf.ProtoMember(3, Name = @"header_icon")]
        [global::System.ComponentModel.DefaultValue("")]
        public string HeaderIcon
        {
            get => __pbn__HeaderIcon ?? "";
            set => __pbn__HeaderIcon = value;
        }
        public bool ShouldSerializeHeaderIcon() => __pbn__HeaderIcon != null;
        public void ResetHeaderIcon() => __pbn__HeaderIcon = null;
        private string __pbn__HeaderIcon;

        [global::ProtoBuf.ProtoMember(4, Name = @"icon_color")]
        [global::System.ComponentModel.DefaultValue("")]
        public string IconColor
        {
            get => __pbn__IconColor ?? "";
            set => __pbn__IconColor = value;
        }
        public bool ShouldSerializeIconColor() => __pbn__IconColor != null;
        public void ResetIconColor() => __pbn__IconColor = null;
        private string __pbn__IconColor;

        [global::ProtoBuf.ProtoContract()]
        public partial class DebugLinkShowTextItem : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"style")]
            [global::System.ComponentModel.DefaultValue(DebugLinkShowText.DebugLinkShowTextStyle.Normal)]
            public DebugLinkShowText.DebugLinkShowTextStyle Style
            {
                get => __pbn__Style ?? DebugLinkShowText.DebugLinkShowTextStyle.Normal;
                set => __pbn__Style = value;
            }
            public bool ShouldSerializeStyle() => __pbn__Style != null;
            public void ResetStyle() => __pbn__Style = null;
            private DebugLinkShowText.DebugLinkShowTextStyle? __pbn__Style;

            [global::ProtoBuf.ProtoMember(2, Name = @"content")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Content
            {
                get => __pbn__Content ?? "";
                set => __pbn__Content = value;
            }
            public bool ShouldSerializeContent() => __pbn__Content != null;
            public void ResetContent() => __pbn__Content = null;
            private string __pbn__Content;

        }

        [global::ProtoBuf.ProtoContract()]
        public enum DebugLinkShowTextStyle
        {
            [global::ProtoBuf.ProtoEnum(Name = @"NORMAL")]
            Normal = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"BOLD")]
            Bold = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"MONO")]
            Mono = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"MONO_BOLD")]
            MonoBold = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"BR")]
            Br = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"BR_HALF")]
            BrHalf = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"SET_COLOR")]
            SetColor = 6,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkGetState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"wait_word_list")]
        public bool WaitWordList
        {
            get => __pbn__WaitWordList.GetValueOrDefault();
            set => __pbn__WaitWordList = value;
        }
        public bool ShouldSerializeWaitWordList() => __pbn__WaitWordList != null;
        public void ResetWaitWordList() => __pbn__WaitWordList = null;
        private bool? __pbn__WaitWordList;

        [global::ProtoBuf.ProtoMember(2, Name = @"wait_word_pos")]
        public bool WaitWordPos
        {
            get => __pbn__WaitWordPos.GetValueOrDefault();
            set => __pbn__WaitWordPos = value;
        }
        public bool ShouldSerializeWaitWordPos() => __pbn__WaitWordPos != null;
        public void ResetWaitWordPos() => __pbn__WaitWordPos = null;
        private bool? __pbn__WaitWordPos;

        [global::ProtoBuf.ProtoMember(3, Name = @"wait_layout")]
        public bool WaitLayout
        {
            get => __pbn__WaitLayout.GetValueOrDefault();
            set => __pbn__WaitLayout = value;
        }
        public bool ShouldSerializeWaitLayout() => __pbn__WaitLayout != null;
        public void ResetWaitLayout() => __pbn__WaitLayout = null;
        private bool? __pbn__WaitLayout;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"layout")]
        public byte[] Layout
        {
            get => __pbn__Layout;
            set => __pbn__Layout = value;
        }
        public bool ShouldSerializeLayout() => __pbn__Layout != null;
        public void ResetLayout() => __pbn__Layout = null;
        private byte[] __pbn__Layout;

        [global::ProtoBuf.ProtoMember(2, Name = @"pin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Pin
        {
            get => __pbn__Pin ?? "";
            set => __pbn__Pin = value;
        }
        public bool ShouldSerializePin() => __pbn__Pin != null;
        public void ResetPin() => __pbn__Pin = null;
        private string __pbn__Pin;

        [global::ProtoBuf.ProtoMember(3, Name = @"matrix")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Matrix
        {
            get => __pbn__Matrix ?? "";
            set => __pbn__Matrix = value;
        }
        public bool ShouldSerializeMatrix() => __pbn__Matrix != null;
        public void ResetMatrix() => __pbn__Matrix = null;
        private string __pbn__Matrix;

        [global::ProtoBuf.ProtoMember(4, Name = @"mnemonic_secret")]
        public byte[] MnemonicSecret
        {
            get => __pbn__MnemonicSecret;
            set => __pbn__MnemonicSecret = value;
        }
        public bool ShouldSerializeMnemonicSecret() => __pbn__MnemonicSecret != null;
        public void ResetMnemonicSecret() => __pbn__MnemonicSecret = null;
        private byte[] __pbn__MnemonicSecret;

        [global::ProtoBuf.ProtoMember(5, Name = @"node")]
        public HDNodeType Node { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"passphrase_protection")]
        public bool PassphraseProtection
        {
            get => __pbn__PassphraseProtection.GetValueOrDefault();
            set => __pbn__PassphraseProtection = value;
        }
        public bool ShouldSerializePassphraseProtection() => __pbn__PassphraseProtection != null;
        public void ResetPassphraseProtection() => __pbn__PassphraseProtection = null;
        private bool? __pbn__PassphraseProtection;

        [global::ProtoBuf.ProtoMember(7, Name = @"reset_word")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ResetWord
        {
            get => __pbn__ResetWord ?? "";
            set => __pbn__ResetWord = value;
        }
        public bool ShouldSerializeResetWord() => __pbn__ResetWord != null;
        public void ResetResetWord() => __pbn__ResetWord = null;
        private string __pbn__ResetWord;

        [global::ProtoBuf.ProtoMember(8, Name = @"reset_entropy")]
        public byte[] ResetEntropy
        {
            get => __pbn__ResetEntropy;
            set => __pbn__ResetEntropy = value;
        }
        public bool ShouldSerializeResetEntropy() => __pbn__ResetEntropy != null;
        public void ResetResetEntropy() => __pbn__ResetEntropy = null;
        private byte[] __pbn__ResetEntropy;

        [global::ProtoBuf.ProtoMember(9, Name = @"recovery_fake_word")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RecoveryFakeWord
        {
            get => __pbn__RecoveryFakeWord ?? "";
            set => __pbn__RecoveryFakeWord = value;
        }
        public bool ShouldSerializeRecoveryFakeWord() => __pbn__RecoveryFakeWord != null;
        public void ResetRecoveryFakeWord() => __pbn__RecoveryFakeWord = null;
        private string __pbn__RecoveryFakeWord;

        [global::ProtoBuf.ProtoMember(10, Name = @"recovery_word_pos")]
        public uint RecoveryWordPos
        {
            get => __pbn__RecoveryWordPos.GetValueOrDefault();
            set => __pbn__RecoveryWordPos = value;
        }
        public bool ShouldSerializeRecoveryWordPos() => __pbn__RecoveryWordPos != null;
        public void ResetRecoveryWordPos() => __pbn__RecoveryWordPos = null;
        private uint? __pbn__RecoveryWordPos;

        [global::ProtoBuf.ProtoMember(11, Name = @"reset_word_pos")]
        public uint ResetWordPos
        {
            get => __pbn__ResetWordPos.GetValueOrDefault();
            set => __pbn__ResetWordPos = value;
        }
        public bool ShouldSerializeResetWordPos() => __pbn__ResetWordPos != null;
        public void ResetResetWordPos() => __pbn__ResetWordPos = null;
        private uint? __pbn__ResetWordPos;

        [global::ProtoBuf.ProtoMember(12, Name = @"mnemonic_type")]
        public uint MnemonicType
        {
            get => __pbn__MnemonicType.GetValueOrDefault();
            set => __pbn__MnemonicType = value;
        }
        public bool ShouldSerializeMnemonicType() => __pbn__MnemonicType != null;
        public void ResetMnemonicType() => __pbn__MnemonicType = null;
        private uint? __pbn__MnemonicType;

        [global::ProtoBuf.ProtoMember(13, Name = @"layout_lines")]
        public global::System.Collections.Generic.List<string> LayoutLines { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkStop : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkLog : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

        [global::ProtoBuf.ProtoMember(2, Name = @"bucket")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Bucket
        {
            get => __pbn__Bucket ?? "";
            set => __pbn__Bucket = value;
        }
        public bool ShouldSerializeBucket() => __pbn__Bucket != null;
        public void ResetBucket() => __pbn__Bucket = null;
        private string __pbn__Bucket;

        [global::ProtoBuf.ProtoMember(3, Name = @"text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Text
        {
            get => __pbn__Text ?? "";
            set => __pbn__Text = value;
        }
        public bool ShouldSerializeText() => __pbn__Text != null;
        public void ResetText() => __pbn__Text = null;
        private string __pbn__Text;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkMemoryRead : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        public uint Address
        {
            get => __pbn__Address.GetValueOrDefault();
            set => __pbn__Address = value;
        }
        public bool ShouldSerializeAddress() => __pbn__Address != null;
        public void ResetAddress() => __pbn__Address = null;
        private uint? __pbn__Address;

        [global::ProtoBuf.ProtoMember(2, Name = @"length")]
        public uint Length
        {
            get => __pbn__Length.GetValueOrDefault();
            set => __pbn__Length = value;
        }
        public bool ShouldSerializeLength() => __pbn__Length != null;
        public void ResetLength() => __pbn__Length = null;
        private uint? __pbn__Length;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkMemory : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"memory")]
        public byte[] Memory
        {
            get => __pbn__Memory;
            set => __pbn__Memory = value;
        }
        public bool ShouldSerializeMemory() => __pbn__Memory != null;
        public void ResetMemory() => __pbn__Memory = null;
        private byte[] __pbn__Memory;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkMemoryWrite : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        public uint Address
        {
            get => __pbn__Address.GetValueOrDefault();
            set => __pbn__Address = value;
        }
        public bool ShouldSerializeAddress() => __pbn__Address != null;
        public void ResetAddress() => __pbn__Address = null;
        private uint? __pbn__Address;

        [global::ProtoBuf.ProtoMember(2, Name = @"memory")]
        public byte[] Memory
        {
            get => __pbn__Memory;
            set => __pbn__Memory = value;
        }
        public bool ShouldSerializeMemory() => __pbn__Memory != null;
        public void ResetMemory() => __pbn__Memory = null;
        private byte[] __pbn__Memory;

        [global::ProtoBuf.ProtoMember(3, Name = @"flash")]
        public bool Flash
        {
            get => __pbn__Flash.GetValueOrDefault();
            set => __pbn__Flash = value;
        }
        public bool ShouldSerializeFlash() => __pbn__Flash != null;
        public void ResetFlash() => __pbn__Flash = null;
        private bool? __pbn__Flash;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkFlashErase : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sector")]
        public uint Sector
        {
            get => __pbn__Sector.GetValueOrDefault();
            set => __pbn__Sector = value;
        }
        public bool ShouldSerializeSector() => __pbn__Sector != null;
        public void ResetSector() => __pbn__Sector = null;
        private uint? __pbn__Sector;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkEraseSdCard : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"format")]
        public bool Format
        {
            get => __pbn__Format.GetValueOrDefault();
            set => __pbn__Format = value;
        }
        public bool ShouldSerializeFormat() => __pbn__Format != null;
        public void ResetFormat() => __pbn__Format = null;
        private bool? __pbn__Format;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugLinkWatchLayout : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"watch")]
        public bool Watch
        {
            get => __pbn__Watch.GetValueOrDefault();
            set => __pbn__Watch = value;
        }
        public bool ShouldSerializeWatch() => __pbn__Watch != null;
        public void ResetWatch() => __pbn__Watch = null;
        private bool? __pbn__Watch;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
