// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: messages-monero.proto

#pragma warning disable
namespace Trezor.Net.Contracts.Monero
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionSourceEntry : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"outputs")]
        public global::System.Collections.Generic.List<MoneroOutputEntry> Outputs { get; } = new global::System.Collections.Generic.List<MoneroOutputEntry>();

        [global::ProtoBuf.ProtoMember(2, Name = @"real_output")]
        public ulong RealOutput
        {
            get { return __pbn__RealOutput.GetValueOrDefault(); }
            set { __pbn__RealOutput = value; }
        }
        public bool ShouldSerializeRealOutput() => __pbn__RealOutput != null;
        public void ResetRealOutput() => __pbn__RealOutput = null;
        private ulong? __pbn__RealOutput;

        [global::ProtoBuf.ProtoMember(3, Name = @"real_out_tx_key")]
        public byte[] RealOutTxKey
        {
            get { return __pbn__RealOutTxKey; }
            set { __pbn__RealOutTxKey = value; }
        }
        public bool ShouldSerializeRealOutTxKey() => __pbn__RealOutTxKey != null;
        public void ResetRealOutTxKey() => __pbn__RealOutTxKey = null;
        private byte[] __pbn__RealOutTxKey;

        [global::ProtoBuf.ProtoMember(4, Name = @"real_out_additional_tx_keys")]
        public global::System.Collections.Generic.List<byte[]> RealOutAdditionalTxKeys { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(5, Name = @"real_output_in_tx_index")]
        public ulong RealOutputInTxIndex
        {
            get { return __pbn__RealOutputInTxIndex.GetValueOrDefault(); }
            set { __pbn__RealOutputInTxIndex = value; }
        }
        public bool ShouldSerializeRealOutputInTxIndex() => __pbn__RealOutputInTxIndex != null;
        public void ResetRealOutputInTxIndex() => __pbn__RealOutputInTxIndex = null;
        private ulong? __pbn__RealOutputInTxIndex;

        [global::ProtoBuf.ProtoMember(6, Name = @"amount")]
        public ulong Amount
        {
            get { return __pbn__Amount.GetValueOrDefault(); }
            set { __pbn__Amount = value; }
        }
        public bool ShouldSerializeAmount() => __pbn__Amount != null;
        public void ResetAmount() => __pbn__Amount = null;
        private ulong? __pbn__Amount;

        [global::ProtoBuf.ProtoMember(7, Name = @"rct")]
        public bool Rct
        {
            get { return __pbn__Rct.GetValueOrDefault(); }
            set { __pbn__Rct = value; }
        }
        public bool ShouldSerializeRct() => __pbn__Rct != null;
        public void ResetRct() => __pbn__Rct = null;
        private bool? __pbn__Rct;

        [global::ProtoBuf.ProtoMember(8, Name = @"mask")]
        public byte[] Mask
        {
            get { return __pbn__Mask; }
            set { __pbn__Mask = value; }
        }
        public bool ShouldSerializeMask() => __pbn__Mask != null;
        public void ResetMask() => __pbn__Mask = null;
        private byte[] __pbn__Mask;

        [global::ProtoBuf.ProtoMember(9, Name = @"multisig_kLRki")]
        public MoneroMultisigKLRki multisigkLRki { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class MoneroOutputEntry : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"idx")]
            public ulong Idx
            {
                get { return __pbn__Idx.GetValueOrDefault(); }
                set { __pbn__Idx = value; }
            }
            public bool ShouldSerializeIdx() => __pbn__Idx != null;
            public void ResetIdx() => __pbn__Idx = null;
            private ulong? __pbn__Idx;

            [global::ProtoBuf.ProtoMember(2, Name = @"key")]
            public MoneroRctKeyPublic Key { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class MoneroRctKeyPublic : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"dest")]
                public byte[] Dest
                {
                    get { return __pbn__Dest; }
                    set { __pbn__Dest = value; }
                }
                public bool ShouldSerializeDest() => __pbn__Dest != null;
                public void ResetDest() => __pbn__Dest = null;
                private byte[] __pbn__Dest;

                [global::ProtoBuf.ProtoMember(2, Name = @"commitment")]
                public byte[] Commitment
                {
                    get { return __pbn__Commitment; }
                    set { __pbn__Commitment = value; }
                }
                public bool ShouldSerializeCommitment() => __pbn__Commitment != null;
                public void ResetCommitment() => __pbn__Commitment = null;
                private byte[] __pbn__Commitment;

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class MoneroMultisigKLRki : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public byte[] K
            {
                get { return __pbn__K; }
                set { __pbn__K = value; }
            }
            public bool ShouldSerializeK() => __pbn__K != null;
            public void ResetK() => __pbn__K = null;
            private byte[] __pbn__K;

            [global::ProtoBuf.ProtoMember(2)]
            public byte[] L
            {
                get { return __pbn__L; }
                set { __pbn__L = value; }
            }
            public bool ShouldSerializeL() => __pbn__L != null;
            public void ResetL() => __pbn__L = null;
            private byte[] __pbn__L;

            [global::ProtoBuf.ProtoMember(3)]
            public byte[] R
            {
                get { return __pbn__R; }
                set { __pbn__R = value; }
            }
            public bool ShouldSerializeR() => __pbn__R != null;
            public void ResetR() => __pbn__R = null;
            private byte[] __pbn__R;

            [global::ProtoBuf.ProtoMember(4, Name = @"ki")]
            public byte[] Ki
            {
                get { return __pbn__Ki; }
                set { __pbn__Ki = value; }
            }
            public bool ShouldSerializeKi() => __pbn__Ki != null;
            public void ResetKi() => __pbn__Ki = null;
            private byte[] __pbn__Ki;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionDestinationEntry : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"amount")]
        public ulong Amount
        {
            get { return __pbn__Amount.GetValueOrDefault(); }
            set { __pbn__Amount = value; }
        }
        public bool ShouldSerializeAmount() => __pbn__Amount != null;
        public void ResetAmount() => __pbn__Amount = null;
        private ulong? __pbn__Amount;

        [global::ProtoBuf.ProtoMember(2, Name = @"addr")]
        public MoneroAccountPublicAddress Addr { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"is_subaddress")]
        public bool IsSubaddress
        {
            get { return __pbn__IsSubaddress.GetValueOrDefault(); }
            set { __pbn__IsSubaddress = value; }
        }
        public bool ShouldSerializeIsSubaddress() => __pbn__IsSubaddress != null;
        public void ResetIsSubaddress() => __pbn__IsSubaddress = null;
        private bool? __pbn__IsSubaddress;

        [global::ProtoBuf.ProtoMember(4, Name = @"original")]
        public byte[] Original
        {
            get { return __pbn__Original; }
            set { __pbn__Original = value; }
        }
        public bool ShouldSerializeOriginal() => __pbn__Original != null;
        public void ResetOriginal() => __pbn__Original = null;
        private byte[] __pbn__Original;

        [global::ProtoBuf.ProtoMember(5, Name = @"is_integrated")]
        public bool IsIntegrated
        {
            get { return __pbn__IsIntegrated.GetValueOrDefault(); }
            set { __pbn__IsIntegrated = value; }
        }
        public bool ShouldSerializeIsIntegrated() => __pbn__IsIntegrated != null;
        public void ResetIsIntegrated() => __pbn__IsIntegrated = null;
        private bool? __pbn__IsIntegrated;

        [global::ProtoBuf.ProtoContract()]
        public partial class MoneroAccountPublicAddress : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"spend_public_key")]
            public byte[] SpendPublicKey
            {
                get { return __pbn__SpendPublicKey; }
                set { __pbn__SpendPublicKey = value; }
            }
            public bool ShouldSerializeSpendPublicKey() => __pbn__SpendPublicKey != null;
            public void ResetSpendPublicKey() => __pbn__SpendPublicKey = null;
            private byte[] __pbn__SpendPublicKey;

            [global::ProtoBuf.ProtoMember(2, Name = @"view_public_key")]
            public byte[] ViewPublicKey
            {
                get { return __pbn__ViewPublicKey; }
                set { __pbn__ViewPublicKey = value; }
            }
            public bool ShouldSerializeViewPublicKey() => __pbn__ViewPublicKey != null;
            public void ResetViewPublicKey() => __pbn__ViewPublicKey = null;
            private byte[] __pbn__ViewPublicKey;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionRsigData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"rsig_type")]
        public uint RsigType
        {
            get { return __pbn__RsigType.GetValueOrDefault(); }
            set { __pbn__RsigType = value; }
        }
        public bool ShouldSerializeRsigType() => __pbn__RsigType != null;
        public void ResetRsigType() => __pbn__RsigType = null;
        private uint? __pbn__RsigType;

        [global::ProtoBuf.ProtoMember(2, Name = @"offload_type")]
        public uint OffloadType
        {
            get { return __pbn__OffloadType.GetValueOrDefault(); }
            set { __pbn__OffloadType = value; }
        }
        public bool ShouldSerializeOffloadType() => __pbn__OffloadType != null;
        public void ResetOffloadType() => __pbn__OffloadType = null;
        private uint? __pbn__OffloadType;

        [global::ProtoBuf.ProtoMember(3, Name = @"grouping")]
        public ulong[] Groupings { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"mask")]
        public byte[] Mask
        {
            get { return __pbn__Mask; }
            set { __pbn__Mask = value; }
        }
        public bool ShouldSerializeMask() => __pbn__Mask != null;
        public void ResetMask() => __pbn__Mask = null;
        private byte[] __pbn__Mask;

        [global::ProtoBuf.ProtoMember(5, Name = @"rsig")]
        public byte[] Rsig
        {
            get { return __pbn__Rsig; }
            set { __pbn__Rsig = value; }
        }
        public bool ShouldSerializeRsig() => __pbn__Rsig != null;
        public void ResetRsig() => __pbn__Rsig = null;
        private byte[] __pbn__Rsig;

        [global::ProtoBuf.ProtoMember(6, Name = @"rsig_parts")]
        public global::System.Collections.Generic.List<byte[]> RsigParts { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(7, Name = @"bp_version")]
        public uint BpVersion
        {
            get { return __pbn__BpVersion.GetValueOrDefault(); }
            set { __pbn__BpVersion = value; }
        }
        public bool ShouldSerializeBpVersion() => __pbn__BpVersion != null;
        public void ResetBpVersion() => __pbn__BpVersion = null;
        private uint? __pbn__BpVersion;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroGetAddress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"show_display")]
        public bool ShowDisplay
        {
            get { return __pbn__ShowDisplay.GetValueOrDefault(); }
            set { __pbn__ShowDisplay = value; }
        }
        public bool ShouldSerializeShowDisplay() => __pbn__ShowDisplay != null;
        public void ResetShowDisplay() => __pbn__ShowDisplay = null;
        private bool? __pbn__ShowDisplay;

        [global::ProtoBuf.ProtoMember(3, Name = @"network_type")]
        public uint NetworkType
        {
            get { return __pbn__NetworkType.GetValueOrDefault(); }
            set { __pbn__NetworkType = value; }
        }
        public bool ShouldSerializeNetworkType() => __pbn__NetworkType != null;
        public void ResetNetworkType() => __pbn__NetworkType = null;
        private uint? __pbn__NetworkType;

        [global::ProtoBuf.ProtoMember(4, Name = @"account")]
        public uint Account
        {
            get { return __pbn__Account.GetValueOrDefault(); }
            set { __pbn__Account = value; }
        }
        public bool ShouldSerializeAccount() => __pbn__Account != null;
        public void ResetAccount() => __pbn__Account = null;
        private uint? __pbn__Account;

        [global::ProtoBuf.ProtoMember(5, Name = @"minor")]
        public uint Minor
        {
            get { return __pbn__Minor.GetValueOrDefault(); }
            set { __pbn__Minor = value; }
        }
        public bool ShouldSerializeMinor() => __pbn__Minor != null;
        public void ResetMinor() => __pbn__Minor = null;
        private uint? __pbn__Minor;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroAddress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        public byte[] Address
        {
            get { return __pbn__Address; }
            set { __pbn__Address = value; }
        }
        public bool ShouldSerializeAddress() => __pbn__Address != null;
        public void ResetAddress() => __pbn__Address = null;
        private byte[] __pbn__Address;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroGetWatchKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"network_type")]
        public uint NetworkType
        {
            get { return __pbn__NetworkType.GetValueOrDefault(); }
            set { __pbn__NetworkType = value; }
        }
        public bool ShouldSerializeNetworkType() => __pbn__NetworkType != null;
        public void ResetNetworkType() => __pbn__NetworkType = null;
        private uint? __pbn__NetworkType;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroWatchKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"watch_key")]
        public byte[] WatchKey
        {
            get { return __pbn__WatchKey; }
            set { __pbn__WatchKey = value; }
        }
        public bool ShouldSerializeWatchKey() => __pbn__WatchKey != null;
        public void ResetWatchKey() => __pbn__WatchKey = null;
        private byte[] __pbn__WatchKey;

        [global::ProtoBuf.ProtoMember(2, Name = @"address")]
        public byte[] Address
        {
            get { return __pbn__Address; }
            set { __pbn__Address = value; }
        }
        public bool ShouldSerializeAddress() => __pbn__Address != null;
        public void ResetAddress() => __pbn__Address = null;
        private byte[] __pbn__Address;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionInitRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"version")]
        public uint Version
        {
            get { return __pbn__Version.GetValueOrDefault(); }
            set { __pbn__Version = value; }
        }
        public bool ShouldSerializeVersion() => __pbn__Version != null;
        public void ResetVersion() => __pbn__Version = null;
        private uint? __pbn__Version;

        [global::ProtoBuf.ProtoMember(2, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"network_type")]
        public uint NetworkType
        {
            get { return __pbn__NetworkType.GetValueOrDefault(); }
            set { __pbn__NetworkType = value; }
        }
        public bool ShouldSerializeNetworkType() => __pbn__NetworkType != null;
        public void ResetNetworkType() => __pbn__NetworkType = null;
        private uint? __pbn__NetworkType;

        [global::ProtoBuf.ProtoMember(4, Name = @"tsx_data")]
        public MoneroTransactionData TsxData { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class MoneroTransactionData : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"version")]
            public uint Version
            {
                get { return __pbn__Version.GetValueOrDefault(); }
                set { __pbn__Version = value; }
            }
            public bool ShouldSerializeVersion() => __pbn__Version != null;
            public void ResetVersion() => __pbn__Version = null;
            private uint? __pbn__Version;

            [global::ProtoBuf.ProtoMember(2, Name = @"payment_id")]
            public byte[] PaymentId
            {
                get { return __pbn__PaymentId; }
                set { __pbn__PaymentId = value; }
            }
            public bool ShouldSerializePaymentId() => __pbn__PaymentId != null;
            public void ResetPaymentId() => __pbn__PaymentId = null;
            private byte[] __pbn__PaymentId;

            [global::ProtoBuf.ProtoMember(3, Name = @"unlock_time")]
            public ulong UnlockTime
            {
                get { return __pbn__UnlockTime.GetValueOrDefault(); }
                set { __pbn__UnlockTime = value; }
            }
            public bool ShouldSerializeUnlockTime() => __pbn__UnlockTime != null;
            public void ResetUnlockTime() => __pbn__UnlockTime = null;
            private ulong? __pbn__UnlockTime;

            [global::ProtoBuf.ProtoMember(4, Name = @"outputs")]
            public global::System.Collections.Generic.List<MoneroTransactionDestinationEntry> Outputs { get; } = new global::System.Collections.Generic.List<MoneroTransactionDestinationEntry>();

            [global::ProtoBuf.ProtoMember(5, Name = @"change_dts")]
            public MoneroTransactionDestinationEntry ChangeDts { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"num_inputs")]
            public uint NumInputs
            {
                get { return __pbn__NumInputs.GetValueOrDefault(); }
                set { __pbn__NumInputs = value; }
            }
            public bool ShouldSerializeNumInputs() => __pbn__NumInputs != null;
            public void ResetNumInputs() => __pbn__NumInputs = null;
            private uint? __pbn__NumInputs;

            [global::ProtoBuf.ProtoMember(7, Name = @"mixin")]
            public uint Mixin
            {
                get { return __pbn__Mixin.GetValueOrDefault(); }
                set { __pbn__Mixin = value; }
            }
            public bool ShouldSerializeMixin() => __pbn__Mixin != null;
            public void ResetMixin() => __pbn__Mixin = null;
            private uint? __pbn__Mixin;

            [global::ProtoBuf.ProtoMember(8, Name = @"fee")]
            public ulong Fee
            {
                get { return __pbn__Fee.GetValueOrDefault(); }
                set { __pbn__Fee = value; }
            }
            public bool ShouldSerializeFee() => __pbn__Fee != null;
            public void ResetFee() => __pbn__Fee = null;
            private ulong? __pbn__Fee;

            [global::ProtoBuf.ProtoMember(9, Name = @"account")]
            public uint Account
            {
                get { return __pbn__Account.GetValueOrDefault(); }
                set { __pbn__Account = value; }
            }
            public bool ShouldSerializeAccount() => __pbn__Account != null;
            public void ResetAccount() => __pbn__Account = null;
            private uint? __pbn__Account;

            [global::ProtoBuf.ProtoMember(10, Name = @"minor_indices")]
            public uint[] MinorIndices { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"rsig_data")]
            public MoneroTransactionRsigData RsigData { get; set; }

            [global::ProtoBuf.ProtoMember(12, Name = @"integrated_indices")]
            public uint[] IntegratedIndices { get; set; }

            [global::ProtoBuf.ProtoMember(13, Name = @"client_version")]
            public uint ClientVersion
            {
                get { return __pbn__ClientVersion.GetValueOrDefault(); }
                set { __pbn__ClientVersion = value; }
            }
            public bool ShouldSerializeClientVersion() => __pbn__ClientVersion != null;
            public void ResetClientVersion() => __pbn__ClientVersion = null;
            private uint? __pbn__ClientVersion;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionInitAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"hmacs")]
        public global::System.Collections.Generic.List<byte[]> Hmacs { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(2, Name = @"rsig_data")]
        public MoneroTransactionRsigData RsigData { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionSetInputRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"src_entr")]
        public MoneroTransactionSourceEntry SrcEntr { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionSetInputAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"vini")]
        public byte[] Vini
        {
            get { return __pbn__Vini; }
            set { __pbn__Vini = value; }
        }
        public bool ShouldSerializeVini() => __pbn__Vini != null;
        public void ResetVini() => __pbn__Vini = null;
        private byte[] __pbn__Vini;

        [global::ProtoBuf.ProtoMember(2, Name = @"vini_hmac")]
        public byte[] ViniHmac
        {
            get { return __pbn__ViniHmac; }
            set { __pbn__ViniHmac = value; }
        }
        public bool ShouldSerializeViniHmac() => __pbn__ViniHmac != null;
        public void ResetViniHmac() => __pbn__ViniHmac = null;
        private byte[] __pbn__ViniHmac;

        [global::ProtoBuf.ProtoMember(3, Name = @"pseudo_out")]
        public byte[] PseudoOut
        {
            get { return __pbn__PseudoOut; }
            set { __pbn__PseudoOut = value; }
        }
        public bool ShouldSerializePseudoOut() => __pbn__PseudoOut != null;
        public void ResetPseudoOut() => __pbn__PseudoOut = null;
        private byte[] __pbn__PseudoOut;

        [global::ProtoBuf.ProtoMember(4, Name = @"pseudo_out_hmac")]
        public byte[] PseudoOutHmac
        {
            get { return __pbn__PseudoOutHmac; }
            set { __pbn__PseudoOutHmac = value; }
        }
        public bool ShouldSerializePseudoOutHmac() => __pbn__PseudoOutHmac != null;
        public void ResetPseudoOutHmac() => __pbn__PseudoOutHmac = null;
        private byte[] __pbn__PseudoOutHmac;

        [global::ProtoBuf.ProtoMember(5, Name = @"pseudo_out_alpha")]
        public byte[] PseudoOutAlpha
        {
            get { return __pbn__PseudoOutAlpha; }
            set { __pbn__PseudoOutAlpha = value; }
        }
        public bool ShouldSerializePseudoOutAlpha() => __pbn__PseudoOutAlpha != null;
        public void ResetPseudoOutAlpha() => __pbn__PseudoOutAlpha = null;
        private byte[] __pbn__PseudoOutAlpha;

        [global::ProtoBuf.ProtoMember(6, Name = @"spend_key")]
        public byte[] SpendKey
        {
            get { return __pbn__SpendKey; }
            set { __pbn__SpendKey = value; }
        }
        public bool ShouldSerializeSpendKey() => __pbn__SpendKey != null;
        public void ResetSpendKey() => __pbn__SpendKey = null;
        private byte[] __pbn__SpendKey;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionInputsPermutationRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"perm")]
        public uint[] Perms { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionInputsPermutationAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionInputViniRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"src_entr")]
        public MoneroTransactionSourceEntry SrcEntr { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"vini")]
        public byte[] Vini
        {
            get { return __pbn__Vini; }
            set { __pbn__Vini = value; }
        }
        public bool ShouldSerializeVini() => __pbn__Vini != null;
        public void ResetVini() => __pbn__Vini = null;
        private byte[] __pbn__Vini;

        [global::ProtoBuf.ProtoMember(3, Name = @"vini_hmac")]
        public byte[] ViniHmac
        {
            get { return __pbn__ViniHmac; }
            set { __pbn__ViniHmac = value; }
        }
        public bool ShouldSerializeViniHmac() => __pbn__ViniHmac != null;
        public void ResetViniHmac() => __pbn__ViniHmac = null;
        private byte[] __pbn__ViniHmac;

        [global::ProtoBuf.ProtoMember(4, Name = @"pseudo_out")]
        public byte[] PseudoOut
        {
            get { return __pbn__PseudoOut; }
            set { __pbn__PseudoOut = value; }
        }
        public bool ShouldSerializePseudoOut() => __pbn__PseudoOut != null;
        public void ResetPseudoOut() => __pbn__PseudoOut = null;
        private byte[] __pbn__PseudoOut;

        [global::ProtoBuf.ProtoMember(5, Name = @"pseudo_out_hmac")]
        public byte[] PseudoOutHmac
        {
            get { return __pbn__PseudoOutHmac; }
            set { __pbn__PseudoOutHmac = value; }
        }
        public bool ShouldSerializePseudoOutHmac() => __pbn__PseudoOutHmac != null;
        public void ResetPseudoOutHmac() => __pbn__PseudoOutHmac = null;
        private byte[] __pbn__PseudoOutHmac;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionInputViniAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionAllInputsSetRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionAllInputsSetAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"rsig_data")]
        public MoneroTransactionRsigData RsigData { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionSetOutputRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"dst_entr")]
        public MoneroTransactionDestinationEntry DstEntr { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"dst_entr_hmac")]
        public byte[] DstEntrHmac
        {
            get { return __pbn__DstEntrHmac; }
            set { __pbn__DstEntrHmac = value; }
        }
        public bool ShouldSerializeDstEntrHmac() => __pbn__DstEntrHmac != null;
        public void ResetDstEntrHmac() => __pbn__DstEntrHmac = null;
        private byte[] __pbn__DstEntrHmac;

        [global::ProtoBuf.ProtoMember(3, Name = @"rsig_data")]
        public MoneroTransactionRsigData RsigData { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"is_offloaded_bp")]
        public bool IsOffloadedBp
        {
            get { return __pbn__IsOffloadedBp.GetValueOrDefault(); }
            set { __pbn__IsOffloadedBp = value; }
        }
        public bool ShouldSerializeIsOffloadedBp() => __pbn__IsOffloadedBp != null;
        public void ResetIsOffloadedBp() => __pbn__IsOffloadedBp = null;
        private bool? __pbn__IsOffloadedBp;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionSetOutputAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tx_out")]
        public byte[] TxOut
        {
            get { return __pbn__TxOut; }
            set { __pbn__TxOut = value; }
        }
        public bool ShouldSerializeTxOut() => __pbn__TxOut != null;
        public void ResetTxOut() => __pbn__TxOut = null;
        private byte[] __pbn__TxOut;

        [global::ProtoBuf.ProtoMember(2, Name = @"vouti_hmac")]
        public byte[] VoutiHmac
        {
            get { return __pbn__VoutiHmac; }
            set { __pbn__VoutiHmac = value; }
        }
        public bool ShouldSerializeVoutiHmac() => __pbn__VoutiHmac != null;
        public void ResetVoutiHmac() => __pbn__VoutiHmac = null;
        private byte[] __pbn__VoutiHmac;

        [global::ProtoBuf.ProtoMember(3, Name = @"rsig_data")]
        public MoneroTransactionRsigData RsigData { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"out_pk")]
        public byte[] OutPk
        {
            get { return __pbn__OutPk; }
            set { __pbn__OutPk = value; }
        }
        public bool ShouldSerializeOutPk() => __pbn__OutPk != null;
        public void ResetOutPk() => __pbn__OutPk = null;
        private byte[] __pbn__OutPk;

        [global::ProtoBuf.ProtoMember(5, Name = @"ecdh_info")]
        public byte[] EcdhInfo
        {
            get { return __pbn__EcdhInfo; }
            set { __pbn__EcdhInfo = value; }
        }
        public bool ShouldSerializeEcdhInfo() => __pbn__EcdhInfo != null;
        public void ResetEcdhInfo() => __pbn__EcdhInfo = null;
        private byte[] __pbn__EcdhInfo;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionAllOutSetRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"rsig_data")]
        public MoneroTransactionRsigData RsigData { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionAllOutSetAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"extra")]
        public byte[] Extra
        {
            get { return __pbn__Extra; }
            set { __pbn__Extra = value; }
        }
        public bool ShouldSerializeExtra() => __pbn__Extra != null;
        public void ResetExtra() => __pbn__Extra = null;
        private byte[] __pbn__Extra;

        [global::ProtoBuf.ProtoMember(2, Name = @"tx_prefix_hash")]
        public byte[] TxPrefixHash
        {
            get { return __pbn__TxPrefixHash; }
            set { __pbn__TxPrefixHash = value; }
        }
        public bool ShouldSerializeTxPrefixHash() => __pbn__TxPrefixHash != null;
        public void ResetTxPrefixHash() => __pbn__TxPrefixHash = null;
        private byte[] __pbn__TxPrefixHash;

        [global::ProtoBuf.ProtoMember(4, Name = @"rv")]
        public MoneroRingCtSig Rv { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"full_message_hash")]
        public byte[] FullMessageHash
        {
            get { return __pbn__FullMessageHash; }
            set { __pbn__FullMessageHash = value; }
        }
        public bool ShouldSerializeFullMessageHash() => __pbn__FullMessageHash != null;
        public void ResetFullMessageHash() => __pbn__FullMessageHash = null;
        private byte[] __pbn__FullMessageHash;

        [global::ProtoBuf.ProtoContract()]
        public partial class MoneroRingCtSig : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"txn_fee")]
            public ulong TxnFee
            {
                get { return __pbn__TxnFee.GetValueOrDefault(); }
                set { __pbn__TxnFee = value; }
            }
            public bool ShouldSerializeTxnFee() => __pbn__TxnFee != null;
            public void ResetTxnFee() => __pbn__TxnFee = null;
            private ulong? __pbn__TxnFee;

            [global::ProtoBuf.ProtoMember(2, Name = @"message")]
            public byte[] Message
            {
                get { return __pbn__Message; }
                set { __pbn__Message = value; }
            }
            public bool ShouldSerializeMessage() => __pbn__Message != null;
            public void ResetMessage() => __pbn__Message = null;
            private byte[] __pbn__Message;

            [global::ProtoBuf.ProtoMember(3, Name = @"rv_type")]
            public uint RvType
            {
                get { return __pbn__RvType.GetValueOrDefault(); }
                set { __pbn__RvType = value; }
            }
            public bool ShouldSerializeRvType() => __pbn__RvType != null;
            public void ResetRvType() => __pbn__RvType = null;
            private uint? __pbn__RvType;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionSignInputRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"src_entr")]
        public MoneroTransactionSourceEntry SrcEntr { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"vini")]
        public byte[] Vini
        {
            get { return __pbn__Vini; }
            set { __pbn__Vini = value; }
        }
        public bool ShouldSerializeVini() => __pbn__Vini != null;
        public void ResetVini() => __pbn__Vini = null;
        private byte[] __pbn__Vini;

        [global::ProtoBuf.ProtoMember(3, Name = @"vini_hmac")]
        public byte[] ViniHmac
        {
            get { return __pbn__ViniHmac; }
            set { __pbn__ViniHmac = value; }
        }
        public bool ShouldSerializeViniHmac() => __pbn__ViniHmac != null;
        public void ResetViniHmac() => __pbn__ViniHmac = null;
        private byte[] __pbn__ViniHmac;

        [global::ProtoBuf.ProtoMember(4, Name = @"pseudo_out")]
        public byte[] PseudoOut
        {
            get { return __pbn__PseudoOut; }
            set { __pbn__PseudoOut = value; }
        }
        public bool ShouldSerializePseudoOut() => __pbn__PseudoOut != null;
        public void ResetPseudoOut() => __pbn__PseudoOut = null;
        private byte[] __pbn__PseudoOut;

        [global::ProtoBuf.ProtoMember(5, Name = @"pseudo_out_hmac")]
        public byte[] PseudoOutHmac
        {
            get { return __pbn__PseudoOutHmac; }
            set { __pbn__PseudoOutHmac = value; }
        }
        public bool ShouldSerializePseudoOutHmac() => __pbn__PseudoOutHmac != null;
        public void ResetPseudoOutHmac() => __pbn__PseudoOutHmac = null;
        private byte[] __pbn__PseudoOutHmac;

        [global::ProtoBuf.ProtoMember(6, Name = @"pseudo_out_alpha")]
        public byte[] PseudoOutAlpha
        {
            get { return __pbn__PseudoOutAlpha; }
            set { __pbn__PseudoOutAlpha = value; }
        }
        public bool ShouldSerializePseudoOutAlpha() => __pbn__PseudoOutAlpha != null;
        public void ResetPseudoOutAlpha() => __pbn__PseudoOutAlpha = null;
        private byte[] __pbn__PseudoOutAlpha;

        [global::ProtoBuf.ProtoMember(7, Name = @"spend_key")]
        public byte[] SpendKey
        {
            get { return __pbn__SpendKey; }
            set { __pbn__SpendKey = value; }
        }
        public bool ShouldSerializeSpendKey() => __pbn__SpendKey != null;
        public void ResetSpendKey() => __pbn__SpendKey = null;
        private byte[] __pbn__SpendKey;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionSignInputAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"signature")]
        public byte[] Signature
        {
            get { return __pbn__Signature; }
            set { __pbn__Signature = value; }
        }
        public bool ShouldSerializeSignature() => __pbn__Signature != null;
        public void ResetSignature() => __pbn__Signature = null;
        private byte[] __pbn__Signature;

        [global::ProtoBuf.ProtoMember(2, Name = @"pseudo_out")]
        public byte[] PseudoOut
        {
            get { return __pbn__PseudoOut; }
            set { __pbn__PseudoOut = value; }
        }
        public bool ShouldSerializePseudoOut() => __pbn__PseudoOut != null;
        public void ResetPseudoOut() => __pbn__PseudoOut = null;
        private byte[] __pbn__PseudoOut;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionFinalRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroTransactionFinalAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cout_key")]
        public byte[] CoutKey
        {
            get { return __pbn__CoutKey; }
            set { __pbn__CoutKey = value; }
        }
        public bool ShouldSerializeCoutKey() => __pbn__CoutKey != null;
        public void ResetCoutKey() => __pbn__CoutKey = null;
        private byte[] __pbn__CoutKey;

        [global::ProtoBuf.ProtoMember(2, Name = @"salt")]
        public byte[] Salt
        {
            get { return __pbn__Salt; }
            set { __pbn__Salt = value; }
        }
        public bool ShouldSerializeSalt() => __pbn__Salt != null;
        public void ResetSalt() => __pbn__Salt = null;
        private byte[] __pbn__Salt;

        [global::ProtoBuf.ProtoMember(3, Name = @"rand_mult")]
        public byte[] RandMult
        {
            get { return __pbn__RandMult; }
            set { __pbn__RandMult = value; }
        }
        public bool ShouldSerializeRandMult() => __pbn__RandMult != null;
        public void ResetRandMult() => __pbn__RandMult = null;
        private byte[] __pbn__RandMult;

        [global::ProtoBuf.ProtoMember(4, Name = @"tx_enc_keys")]
        public byte[] TxEncKeys
        {
            get { return __pbn__TxEncKeys; }
            set { __pbn__TxEncKeys = value; }
        }
        public bool ShouldSerializeTxEncKeys() => __pbn__TxEncKeys != null;
        public void ResetTxEncKeys() => __pbn__TxEncKeys = null;
        private byte[] __pbn__TxEncKeys;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroKeyImageExportInitRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"num")]
        public ulong Num
        {
            get { return __pbn__Num.GetValueOrDefault(); }
            set { __pbn__Num = value; }
        }
        public bool ShouldSerializeNum() => __pbn__Num != null;
        public void ResetNum() => __pbn__Num = null;
        private ulong? __pbn__Num;

        [global::ProtoBuf.ProtoMember(2, Name = @"hash")]
        public byte[] Hash
        {
            get { return __pbn__Hash; }
            set { __pbn__Hash = value; }
        }
        public bool ShouldSerializeHash() => __pbn__Hash != null;
        public void ResetHash() => __pbn__Hash = null;
        private byte[] __pbn__Hash;

        [global::ProtoBuf.ProtoMember(3, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"network_type")]
        public uint NetworkType
        {
            get { return __pbn__NetworkType.GetValueOrDefault(); }
            set { __pbn__NetworkType = value; }
        }
        public bool ShouldSerializeNetworkType() => __pbn__NetworkType != null;
        public void ResetNetworkType() => __pbn__NetworkType = null;
        private uint? __pbn__NetworkType;

        [global::ProtoBuf.ProtoMember(5, Name = @"subs")]
        public global::System.Collections.Generic.List<MoneroSubAddressIndicesList> Subs { get; } = new global::System.Collections.Generic.List<MoneroSubAddressIndicesList>();

        [global::ProtoBuf.ProtoContract()]
        public partial class MoneroSubAddressIndicesList : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"account")]
            public uint Account
            {
                get { return __pbn__Account.GetValueOrDefault(); }
                set { __pbn__Account = value; }
            }
            public bool ShouldSerializeAccount() => __pbn__Account != null;
            public void ResetAccount() => __pbn__Account = null;
            private uint? __pbn__Account;

            [global::ProtoBuf.ProtoMember(2, Name = @"minor_indices")]
            public uint[] MinorIndices { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroKeyImageExportInitAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroKeyImageSyncStepRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tdis")]
        public global::System.Collections.Generic.List<MoneroTransferDetails> Tdes { get; } = new global::System.Collections.Generic.List<MoneroTransferDetails>();

        [global::ProtoBuf.ProtoContract()]
        public partial class MoneroTransferDetails : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"out_key")]
            public byte[] OutKey
            {
                get { return __pbn__OutKey; }
                set { __pbn__OutKey = value; }
            }
            public bool ShouldSerializeOutKey() => __pbn__OutKey != null;
            public void ResetOutKey() => __pbn__OutKey = null;
            private byte[] __pbn__OutKey;

            [global::ProtoBuf.ProtoMember(2, Name = @"tx_pub_key")]
            public byte[] TxPubKey
            {
                get { return __pbn__TxPubKey; }
                set { __pbn__TxPubKey = value; }
            }
            public bool ShouldSerializeTxPubKey() => __pbn__TxPubKey != null;
            public void ResetTxPubKey() => __pbn__TxPubKey = null;
            private byte[] __pbn__TxPubKey;

            [global::ProtoBuf.ProtoMember(3, Name = @"additional_tx_pub_keys")]
            public global::System.Collections.Generic.List<byte[]> AdditionalTxPubKeys { get; } = new global::System.Collections.Generic.List<byte[]>();

            [global::ProtoBuf.ProtoMember(4, Name = @"internal_output_index")]
            public ulong InternalOutputIndex
            {
                get { return __pbn__InternalOutputIndex.GetValueOrDefault(); }
                set { __pbn__InternalOutputIndex = value; }
            }
            public bool ShouldSerializeInternalOutputIndex() => __pbn__InternalOutputIndex != null;
            public void ResetInternalOutputIndex() => __pbn__InternalOutputIndex = null;
            private ulong? __pbn__InternalOutputIndex;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroKeyImageSyncStepAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"kis")]
        public global::System.Collections.Generic.List<MoneroExportedKeyImage> Kes { get; } = new global::System.Collections.Generic.List<MoneroExportedKeyImage>();

        [global::ProtoBuf.ProtoContract()]
        public partial class MoneroExportedKeyImage : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"iv")]
            public byte[] Iv
            {
                get { return __pbn__Iv; }
                set { __pbn__Iv = value; }
            }
            public bool ShouldSerializeIv() => __pbn__Iv != null;
            public void ResetIv() => __pbn__Iv = null;
            private byte[] __pbn__Iv;

            [global::ProtoBuf.ProtoMember(3, Name = @"blob")]
            public byte[] Blob
            {
                get { return __pbn__Blob; }
                set { __pbn__Blob = value; }
            }
            public bool ShouldSerializeBlob() => __pbn__Blob != null;
            public void ResetBlob() => __pbn__Blob = null;
            private byte[] __pbn__Blob;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroKeyImageSyncFinalRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroKeyImageSyncFinalAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"enc_key")]
        public byte[] EncKey
        {
            get { return __pbn__EncKey; }
            set { __pbn__EncKey = value; }
        }
        public bool ShouldSerializeEncKey() => __pbn__EncKey != null;
        public void ResetEncKey() => __pbn__EncKey = null;
        private byte[] __pbn__EncKey;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroGetTxKeyRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"network_type")]
        public uint NetworkType
        {
            get { return __pbn__NetworkType.GetValueOrDefault(); }
            set { __pbn__NetworkType = value; }
        }
        public bool ShouldSerializeNetworkType() => __pbn__NetworkType != null;
        public void ResetNetworkType() => __pbn__NetworkType = null;
        private uint? __pbn__NetworkType;

        [global::ProtoBuf.ProtoMember(3, Name = @"salt1")]
        public byte[] Salt1
        {
            get { return __pbn__Salt1; }
            set { __pbn__Salt1 = value; }
        }
        public bool ShouldSerializeSalt1() => __pbn__Salt1 != null;
        public void ResetSalt1() => __pbn__Salt1 = null;
        private byte[] __pbn__Salt1;

        [global::ProtoBuf.ProtoMember(4, Name = @"salt2")]
        public byte[] Salt2
        {
            get { return __pbn__Salt2; }
            set { __pbn__Salt2 = value; }
        }
        public bool ShouldSerializeSalt2() => __pbn__Salt2 != null;
        public void ResetSalt2() => __pbn__Salt2 = null;
        private byte[] __pbn__Salt2;

        [global::ProtoBuf.ProtoMember(5, Name = @"tx_enc_keys")]
        public byte[] TxEncKeys
        {
            get { return __pbn__TxEncKeys; }
            set { __pbn__TxEncKeys = value; }
        }
        public bool ShouldSerializeTxEncKeys() => __pbn__TxEncKeys != null;
        public void ResetTxEncKeys() => __pbn__TxEncKeys = null;
        private byte[] __pbn__TxEncKeys;

        [global::ProtoBuf.ProtoMember(6, Name = @"tx_prefix_hash")]
        public byte[] TxPrefixHash
        {
            get { return __pbn__TxPrefixHash; }
            set { __pbn__TxPrefixHash = value; }
        }
        public bool ShouldSerializeTxPrefixHash() => __pbn__TxPrefixHash != null;
        public void ResetTxPrefixHash() => __pbn__TxPrefixHash = null;
        private byte[] __pbn__TxPrefixHash;

        [global::ProtoBuf.ProtoMember(7, Name = @"reason")]
        public uint Reason
        {
            get { return __pbn__Reason.GetValueOrDefault(); }
            set { __pbn__Reason = value; }
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private uint? __pbn__Reason;

        [global::ProtoBuf.ProtoMember(8, Name = @"view_public_key")]
        public byte[] ViewPublicKey
        {
            get { return __pbn__ViewPublicKey; }
            set { __pbn__ViewPublicKey = value; }
        }
        public bool ShouldSerializeViewPublicKey() => __pbn__ViewPublicKey != null;
        public void ResetViewPublicKey() => __pbn__ViewPublicKey = null;
        private byte[] __pbn__ViewPublicKey;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroGetTxKeyAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"salt")]
        public byte[] Salt
        {
            get { return __pbn__Salt; }
            set { __pbn__Salt = value; }
        }
        public bool ShouldSerializeSalt() => __pbn__Salt != null;
        public void ResetSalt() => __pbn__Salt = null;
        private byte[] __pbn__Salt;

        [global::ProtoBuf.ProtoMember(2, Name = @"tx_keys")]
        public byte[] TxKeys
        {
            get { return __pbn__TxKeys; }
            set { __pbn__TxKeys = value; }
        }
        public bool ShouldSerializeTxKeys() => __pbn__TxKeys != null;
        public void ResetTxKeys() => __pbn__TxKeys = null;
        private byte[] __pbn__TxKeys;

        [global::ProtoBuf.ProtoMember(3, Name = @"tx_derivations")]
        public byte[] TxDerivations
        {
            get { return __pbn__TxDerivations; }
            set { __pbn__TxDerivations = value; }
        }
        public bool ShouldSerializeTxDerivations() => __pbn__TxDerivations != null;
        public void ResetTxDerivations() => __pbn__TxDerivations = null;
        private byte[] __pbn__TxDerivations;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroLiveRefreshStartRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"network_type")]
        public uint NetworkType
        {
            get { return __pbn__NetworkType.GetValueOrDefault(); }
            set { __pbn__NetworkType = value; }
        }
        public bool ShouldSerializeNetworkType() => __pbn__NetworkType != null;
        public void ResetNetworkType() => __pbn__NetworkType = null;
        private uint? __pbn__NetworkType;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroLiveRefreshStartAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroLiveRefreshStepRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"out_key")]
        public byte[] OutKey
        {
            get { return __pbn__OutKey; }
            set { __pbn__OutKey = value; }
        }
        public bool ShouldSerializeOutKey() => __pbn__OutKey != null;
        public void ResetOutKey() => __pbn__OutKey = null;
        private byte[] __pbn__OutKey;

        [global::ProtoBuf.ProtoMember(2, Name = @"recv_deriv")]
        public byte[] RecvDeriv
        {
            get { return __pbn__RecvDeriv; }
            set { __pbn__RecvDeriv = value; }
        }
        public bool ShouldSerializeRecvDeriv() => __pbn__RecvDeriv != null;
        public void ResetRecvDeriv() => __pbn__RecvDeriv = null;
        private byte[] __pbn__RecvDeriv;

        [global::ProtoBuf.ProtoMember(3, Name = @"real_out_idx")]
        public ulong RealOutIdx
        {
            get { return __pbn__RealOutIdx.GetValueOrDefault(); }
            set { __pbn__RealOutIdx = value; }
        }
        public bool ShouldSerializeRealOutIdx() => __pbn__RealOutIdx != null;
        public void ResetRealOutIdx() => __pbn__RealOutIdx = null;
        private ulong? __pbn__RealOutIdx;

        [global::ProtoBuf.ProtoMember(4, Name = @"sub_addr_major")]
        public uint SubAddrMajor
        {
            get { return __pbn__SubAddrMajor.GetValueOrDefault(); }
            set { __pbn__SubAddrMajor = value; }
        }
        public bool ShouldSerializeSubAddrMajor() => __pbn__SubAddrMajor != null;
        public void ResetSubAddrMajor() => __pbn__SubAddrMajor = null;
        private uint? __pbn__SubAddrMajor;

        [global::ProtoBuf.ProtoMember(5, Name = @"sub_addr_minor")]
        public uint SubAddrMinor
        {
            get { return __pbn__SubAddrMinor.GetValueOrDefault(); }
            set { __pbn__SubAddrMinor = value; }
        }
        public bool ShouldSerializeSubAddrMinor() => __pbn__SubAddrMinor != null;
        public void ResetSubAddrMinor() => __pbn__SubAddrMinor = null;
        private uint? __pbn__SubAddrMinor;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroLiveRefreshStepAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"salt")]
        public byte[] Salt
        {
            get { return __pbn__Salt; }
            set { __pbn__Salt = value; }
        }
        public bool ShouldSerializeSalt() => __pbn__Salt != null;
        public void ResetSalt() => __pbn__Salt = null;
        private byte[] __pbn__Salt;

        [global::ProtoBuf.ProtoMember(2, Name = @"key_image")]
        public byte[] KeyImage
        {
            get { return __pbn__KeyImage; }
            set { __pbn__KeyImage = value; }
        }
        public bool ShouldSerializeKeyImage() => __pbn__KeyImage != null;
        public void ResetKeyImage() => __pbn__KeyImage = null;
        private byte[] __pbn__KeyImage;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroLiveRefreshFinalRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoneroLiveRefreshFinalAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugMoneroDiagRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ins")]
        public ulong Ins
        {
            get { return __pbn__Ins.GetValueOrDefault(); }
            set { __pbn__Ins = value; }
        }
        public bool ShouldSerializeIns() => __pbn__Ins != null;
        public void ResetIns() => __pbn__Ins = null;
        private ulong? __pbn__Ins;

        [global::ProtoBuf.ProtoMember(2, Name = @"p1")]
        public ulong P1
        {
            get { return __pbn__P1.GetValueOrDefault(); }
            set { __pbn__P1 = value; }
        }
        public bool ShouldSerializeP1() => __pbn__P1 != null;
        public void ResetP1() => __pbn__P1 = null;
        private ulong? __pbn__P1;

        [global::ProtoBuf.ProtoMember(3, Name = @"p2")]
        public ulong P2
        {
            get { return __pbn__P2.GetValueOrDefault(); }
            set { __pbn__P2 = value; }
        }
        public bool ShouldSerializeP2() => __pbn__P2 != null;
        public void ResetP2() => __pbn__P2 = null;
        private ulong? __pbn__P2;

        [global::ProtoBuf.ProtoMember(4, Name = @"pd")]
        public ulong[] Pds { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"data1")]
        public byte[] Data1
        {
            get { return __pbn__Data1; }
            set { __pbn__Data1 = value; }
        }
        public bool ShouldSerializeData1() => __pbn__Data1 != null;
        public void ResetData1() => __pbn__Data1 = null;
        private byte[] __pbn__Data1;

        [global::ProtoBuf.ProtoMember(6, Name = @"data2")]
        public byte[] Data2
        {
            get { return __pbn__Data2; }
            set { __pbn__Data2 = value; }
        }
        public bool ShouldSerializeData2() => __pbn__Data2 != null;
        public void ResetData2() => __pbn__Data2 = null;
        private byte[] __pbn__Data2;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugMoneroDiagAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ins")]
        public ulong Ins
        {
            get { return __pbn__Ins.GetValueOrDefault(); }
            set { __pbn__Ins = value; }
        }
        public bool ShouldSerializeIns() => __pbn__Ins != null;
        public void ResetIns() => __pbn__Ins = null;
        private ulong? __pbn__Ins;

        [global::ProtoBuf.ProtoMember(2, Name = @"p1")]
        public ulong P1
        {
            get { return __pbn__P1.GetValueOrDefault(); }
            set { __pbn__P1 = value; }
        }
        public bool ShouldSerializeP1() => __pbn__P1 != null;
        public void ResetP1() => __pbn__P1 = null;
        private ulong? __pbn__P1;

        [global::ProtoBuf.ProtoMember(3, Name = @"p2")]
        public ulong P2
        {
            get { return __pbn__P2.GetValueOrDefault(); }
            set { __pbn__P2 = value; }
        }
        public bool ShouldSerializeP2() => __pbn__P2 != null;
        public void ResetP2() => __pbn__P2 = null;
        private ulong? __pbn__P2;

        [global::ProtoBuf.ProtoMember(4, Name = @"pd")]
        public ulong[] Pds { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"data1")]
        public byte[] Data1
        {
            get { return __pbn__Data1; }
            set { __pbn__Data1 = value; }
        }
        public bool ShouldSerializeData1() => __pbn__Data1 != null;
        public void ResetData1() => __pbn__Data1 = null;
        private byte[] __pbn__Data1;

        [global::ProtoBuf.ProtoMember(6, Name = @"data2")]
        public byte[] Data2
        {
            get { return __pbn__Data2; }
            set { __pbn__Data2 = value; }
        }
        public bool ShouldSerializeData2() => __pbn__Data2 != null;
        public void ResetData2() => __pbn__Data2 = null;
        private byte[] __pbn__Data2;

    }

}

#pragma warning restore
