// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: messages-ethereum.proto

#pragma warning disable
using Trezor.Net.Contracts.Common;

namespace Trezor.Net.Contracts.Ethereum
{

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumGetPublicKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"show_display")]
        public bool ShowDisplay
        {
            get { return __pbn__ShowDisplay.GetValueOrDefault(); }
            set { __pbn__ShowDisplay = value; }
        }
        public bool ShouldSerializeShowDisplay() => __pbn__ShowDisplay != null;
        public void ResetShowDisplay() => __pbn__ShowDisplay = null;
        private bool? __pbn__ShowDisplay;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumPublicKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"node")]
        public HDNodeType Node { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"xpub")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Xpub
        {
            get { return __pbn__Xpub ?? ""; }
            set { __pbn__Xpub = value; }
        }
        public bool ShouldSerializeXpub() => __pbn__Xpub != null;
        public void ResetXpub() => __pbn__Xpub = null;
        private string __pbn__Xpub;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumGetAddress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"show_display")]
        public bool ShowDisplay
        {
            get { return __pbn__ShowDisplay.GetValueOrDefault(); }
            set { __pbn__ShowDisplay = value; }
        }
        public bool ShouldSerializeShowDisplay() => __pbn__ShowDisplay != null;
        public void ResetShowDisplay() => __pbn__ShowDisplay = null;
        private bool? __pbn__ShowDisplay;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumAddress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address
        {
            get { return __pbn__Address ?? ""; }
            set { __pbn__Address = value; }
        }
        public bool ShouldSerializeAddress() => __pbn__Address != null;
        public void ResetAddress() => __pbn__Address = null;
        private string __pbn__Address;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumSignTx : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"nonce")]
        public byte[] Nonce
        {
            get { return __pbn__Nonce; }
            set { __pbn__Nonce = value; }
        }
        public bool ShouldSerializeNonce() => __pbn__Nonce != null;
        public void ResetNonce() => __pbn__Nonce = null;
        private byte[] __pbn__Nonce;

        [global::ProtoBuf.ProtoMember(3, Name = @"gas_price")]
        public byte[] GasPrice
        {
            get { return __pbn__GasPrice; }
            set { __pbn__GasPrice = value; }
        }
        public bool ShouldSerializeGasPrice() => __pbn__GasPrice != null;
        public void ResetGasPrice() => __pbn__GasPrice = null;
        private byte[] __pbn__GasPrice;

        [global::ProtoBuf.ProtoMember(4, Name = @"gas_limit")]
        public byte[] GasLimit
        {
            get { return __pbn__GasLimit; }
            set { __pbn__GasLimit = value; }
        }
        public bool ShouldSerializeGasLimit() => __pbn__GasLimit != null;
        public void ResetGasLimit() => __pbn__GasLimit = null;
        private byte[] __pbn__GasLimit;

        [global::ProtoBuf.ProtoMember(11, Name = @"to")]
        [global::System.ComponentModel.DefaultValue("")]
        public string To
        {
            get { return __pbn__To ?? ""; }
            set { __pbn__To = value; }
        }
        public bool ShouldSerializeTo() => __pbn__To != null;
        public void ResetTo() => __pbn__To = null;
        private string __pbn__To;

        [global::ProtoBuf.ProtoMember(6, Name = @"value")]
        public byte[] Value
        {
            get { return __pbn__Value; }
            set { __pbn__Value = value; }
        }
        public bool ShouldSerializeValue() => __pbn__Value != null;
        public void ResetValue() => __pbn__Value = null;
        private byte[] __pbn__Value;

        [global::ProtoBuf.ProtoMember(7, Name = @"data_initial_chunk")]
        public byte[] DataInitialChunk
        {
            get { return __pbn__DataInitialChunk; }
            set { __pbn__DataInitialChunk = value; }
        }
        public bool ShouldSerializeDataInitialChunk() => __pbn__DataInitialChunk != null;
        public void ResetDataInitialChunk() => __pbn__DataInitialChunk = null;
        private byte[] __pbn__DataInitialChunk;

        [global::ProtoBuf.ProtoMember(8, Name = @"data_length")]
        public uint DataLength
        {
            get { return __pbn__DataLength.GetValueOrDefault(); }
            set { __pbn__DataLength = value; }
        }
        public bool ShouldSerializeDataLength() => __pbn__DataLength != null;
        public void ResetDataLength() => __pbn__DataLength = null;
        private uint? __pbn__DataLength;

        [global::ProtoBuf.ProtoMember(9, Name = @"chain_id")]
        public uint ChainId
        {
            get { return __pbn__ChainId.GetValueOrDefault(); }
            set { __pbn__ChainId = value; }
        }
        public bool ShouldSerializeChainId() => __pbn__ChainId != null;
        public void ResetChainId() => __pbn__ChainId = null;
        private uint? __pbn__ChainId;

        [global::ProtoBuf.ProtoMember(10, Name = @"tx_type")]
        public uint TxType
        {
            get { return __pbn__TxType.GetValueOrDefault(); }
            set { __pbn__TxType = value; }
        }
        public bool ShouldSerializeTxType() => __pbn__TxType != null;
        public void ResetTxType() => __pbn__TxType = null;
        private uint? __pbn__TxType;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumTxRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data_length")]
        public uint DataLength
        {
            get { return __pbn__DataLength.GetValueOrDefault(); }
            set { __pbn__DataLength = value; }
        }
        public bool ShouldSerializeDataLength() => __pbn__DataLength != null;
        public void ResetDataLength() => __pbn__DataLength = null;
        private uint? __pbn__DataLength;

        [global::ProtoBuf.ProtoMember(2, Name = @"signature_v")]
        public uint SignatureV
        {
            get { return __pbn__SignatureV.GetValueOrDefault(); }
            set { __pbn__SignatureV = value; }
        }
        public bool ShouldSerializeSignatureV() => __pbn__SignatureV != null;
        public void ResetSignatureV() => __pbn__SignatureV = null;
        private uint? __pbn__SignatureV;

        [global::ProtoBuf.ProtoMember(3, Name = @"signature_r")]
        public byte[] SignatureR
        {
            get { return __pbn__SignatureR; }
            set { __pbn__SignatureR = value; }
        }
        public bool ShouldSerializeSignatureR() => __pbn__SignatureR != null;
        public void ResetSignatureR() => __pbn__SignatureR = null;
        private byte[] __pbn__SignatureR;

        [global::ProtoBuf.ProtoMember(4, Name = @"signature_s")]
        public byte[] SignatureS
        {
            get { return __pbn__SignatureS; }
            set { __pbn__SignatureS = value; }
        }
        public bool ShouldSerializeSignatureS() => __pbn__SignatureS != null;
        public void ResetSignatureS() => __pbn__SignatureS = null;
        private byte[] __pbn__SignatureS;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumTxAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data_chunk")]
        public byte[] DataChunk
        {
            get { return __pbn__DataChunk; }
            set { __pbn__DataChunk = value; }
        }
        public bool ShouldSerializeDataChunk() => __pbn__DataChunk != null;
        public void ResetDataChunk() => __pbn__DataChunk = null;
        private byte[] __pbn__DataChunk;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumSignMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"message")]
        public byte[] Message
        {
            get { return __pbn__Message; }
            set { __pbn__Message = value; }
        }
        public bool ShouldSerializeMessage() => __pbn__Message != null;
        public void ResetMessage() => __pbn__Message = null;
        private byte[] __pbn__Message;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumMessageSignature : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"signature")]
        public byte[] Signature
        {
            get { return __pbn__Signature; }
            set { __pbn__Signature = value; }
        }
        public bool ShouldSerializeSignature() => __pbn__Signature != null;
        public void ResetSignature() => __pbn__Signature = null;
        private byte[] __pbn__Signature;

        [global::ProtoBuf.ProtoMember(3, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address
        {
            get { return __pbn__Address ?? ""; }
            set { __pbn__Address = value; }
        }
        public bool ShouldSerializeAddress() => __pbn__Address != null;
        public void ResetAddress() => __pbn__Address = null;
        private string __pbn__Address;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EthereumVerifyMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"signature")]
        public byte[] Signature
        {
            get { return __pbn__Signature; }
            set { __pbn__Signature = value; }
        }
        public bool ShouldSerializeSignature() => __pbn__Signature != null;
        public void ResetSignature() => __pbn__Signature = null;
        private byte[] __pbn__Signature;

        [global::ProtoBuf.ProtoMember(3, Name = @"message")]
        public byte[] Message
        {
            get { return __pbn__Message; }
            set { __pbn__Message = value; }
        }
        public bool ShouldSerializeMessage() => __pbn__Message != null;
        public void ResetMessage() => __pbn__Message = null;
        private byte[] __pbn__Message;

        [global::ProtoBuf.ProtoMember(4, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address
        {
            get { return __pbn__Address ?? ""; }
            set { __pbn__Address = value; }
        }
        public bool ShouldSerializeAddress() => __pbn__Address != null;
        public void ResetAddress() => __pbn__Address = null;
        private string __pbn__Address;

    }

}

#pragma warning restore
