// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: messages-eos.proto

#pragma warning disable
namespace hw.trezor.messages.eos
{

    [global::ProtoBuf.ProtoContract()]
    public partial class EosGetPublicKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"show_display")]
        public bool ShowDisplay
        {
            get { return __pbn__ShowDisplay.GetValueOrDefault(); }
            set { __pbn__ShowDisplay = value; }
        }
        public bool ShouldSerializeShowDisplay() => __pbn__ShowDisplay != null;
        public void ResetShowDisplay() => __pbn__ShowDisplay = null;
        private bool? __pbn__ShowDisplay;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EosPublicKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"wif_public_key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string WifPublicKey
        {
            get { return __pbn__WifPublicKey ?? ""; }
            set { __pbn__WifPublicKey = value; }
        }
        public bool ShouldSerializeWifPublicKey() => __pbn__WifPublicKey != null;
        public void ResetWifPublicKey() => __pbn__WifPublicKey = null;
        private string __pbn__WifPublicKey;

        [global::ProtoBuf.ProtoMember(2, Name = @"raw_public_key")]
        public byte[] RawPublicKey
        {
            get { return __pbn__RawPublicKey; }
            set { __pbn__RawPublicKey = value; }
        }
        public bool ShouldSerializeRawPublicKey() => __pbn__RawPublicKey != null;
        public void ResetRawPublicKey() => __pbn__RawPublicKey = null;
        private byte[] __pbn__RawPublicKey;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EosSignTx : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"chain_id")]
        public byte[] ChainId
        {
            get { return __pbn__ChainId; }
            set { __pbn__ChainId = value; }
        }
        public bool ShouldSerializeChainId() => __pbn__ChainId != null;
        public void ResetChainId() => __pbn__ChainId = null;
        private byte[] __pbn__ChainId;

        [global::ProtoBuf.ProtoMember(3, Name = @"header")]
        public EosTxHeader Header { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"num_actions")]
        public uint NumActions
        {
            get { return __pbn__NumActions.GetValueOrDefault(); }
            set { __pbn__NumActions = value; }
        }
        public bool ShouldSerializeNumActions() => __pbn__NumActions != null;
        public void ResetNumActions() => __pbn__NumActions = null;
        private uint? __pbn__NumActions;

        [global::ProtoBuf.ProtoContract()]
        public partial class EosTxHeader : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"expiration", IsRequired = true)]
            public uint Expiration { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"ref_block_num", IsRequired = true)]
            public uint RefBlockNum { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"ref_block_prefix", IsRequired = true)]
            public uint RefBlockPrefix { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"max_net_usage_words", IsRequired = true)]
            public uint MaxNetUsageWords { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"max_cpu_usage_ms", IsRequired = true)]
            public uint MaxCpuUsageMs { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"delay_sec", IsRequired = true)]
            public uint DelaySec { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EosTxActionRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data_size")]
        public uint DataSize
        {
            get { return __pbn__DataSize.GetValueOrDefault(); }
            set { __pbn__DataSize = value; }
        }
        public bool ShouldSerializeDataSize() => __pbn__DataSize != null;
        public void ResetDataSize() => __pbn__DataSize = null;
        private uint? __pbn__DataSize;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EosTxActionAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public EosActionCommon Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"transfer")]
        public EosActionTransfer Transfer { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"delegate")]
        public EosActionDelegate Delegate { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"undelegate")]
        public EosActionUndelegate Undelegate { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"refund")]
        public EosActionRefund Refund { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"buy_ram")]
        public EosActionBuyRam BuyRam { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"buy_ram_bytes")]
        public EosActionBuyRamBytes BuyRamBytes { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"sell_ram")]
        public EosActionSellRam SellRam { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"vote_producer")]
        public EosActionVoteProducer VoteProducer { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"update_auth")]
        public EosActionUpdateAuth UpdateAuth { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"delete_auth")]
        public EosActionDeleteAuth DeleteAuth { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"link_auth")]
        public EosActionLinkAuth LinkAuth { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"unlink_auth")]
        public EosActionUnlinkAuth UnlinkAuth { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"new_account")]
        public EosActionNewAccount NewAccount { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"unknown")]
        public EosActionUnknown Unknown { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosAsset : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"amount", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
            public long Amount
            {
                get { return __pbn__Amount.GetValueOrDefault(); }
                set { __pbn__Amount = value; }
            }
            public bool ShouldSerializeAmount() => __pbn__Amount != null;
            public void ResetAmount() => __pbn__Amount = null;
            private long? __pbn__Amount;

            [global::ProtoBuf.ProtoMember(2, Name = @"symbol")]
            public ulong Symbol
            {
                get { return __pbn__Symbol.GetValueOrDefault(); }
                set { __pbn__Symbol = value; }
            }
            public bool ShouldSerializeSymbol() => __pbn__Symbol != null;
            public void ResetSymbol() => __pbn__Symbol = null;
            private ulong? __pbn__Symbol;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosPermissionLevel : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"actor")]
            public ulong Actor
            {
                get { return __pbn__Actor.GetValueOrDefault(); }
                set { __pbn__Actor = value; }
            }
            public bool ShouldSerializeActor() => __pbn__Actor != null;
            public void ResetActor() => __pbn__Actor = null;
            private ulong? __pbn__Actor;

            [global::ProtoBuf.ProtoMember(2, Name = @"permission")]
            public ulong Permission
            {
                get { return __pbn__Permission.GetValueOrDefault(); }
                set { __pbn__Permission = value; }
            }
            public bool ShouldSerializePermission() => __pbn__Permission != null;
            public void ResetPermission() => __pbn__Permission = null;
            private ulong? __pbn__Permission;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosAuthorizationKey : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"type")]
            public uint Type
            {
                get { return __pbn__Type.GetValueOrDefault(); }
                set { __pbn__Type = value; }
            }
            public bool ShouldSerializeType() => __pbn__Type != null;
            public void ResetType() => __pbn__Type = null;
            private uint? __pbn__Type;

            [global::ProtoBuf.ProtoMember(2, Name = @"key")]
            public byte[] Key
            {
                get { return __pbn__Key; }
                set { __pbn__Key = value; }
            }
            public bool ShouldSerializeKey() => __pbn__Key != null;
            public void ResetKey() => __pbn__Key = null;
            private byte[] __pbn__Key;

            [global::ProtoBuf.ProtoMember(3, Name = @"address_n")]
            public uint[] AddressNs { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"weight")]
            public uint Weight
            {
                get { return __pbn__Weight.GetValueOrDefault(); }
                set { __pbn__Weight = value; }
            }
            public bool ShouldSerializeWeight() => __pbn__Weight != null;
            public void ResetWeight() => __pbn__Weight = null;
            private uint? __pbn__Weight;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosAuthorizationAccount : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"account")]
            public EosTxActionAck.EosPermissionLevel Account { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"weight")]
            public uint Weight
            {
                get { return __pbn__Weight.GetValueOrDefault(); }
                set { __pbn__Weight = value; }
            }
            public bool ShouldSerializeWeight() => __pbn__Weight != null;
            public void ResetWeight() => __pbn__Weight = null;
            private uint? __pbn__Weight;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosAuthorizationWait : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"wait_sec")]
            public uint WaitSec
            {
                get { return __pbn__WaitSec.GetValueOrDefault(); }
                set { __pbn__WaitSec = value; }
            }
            public bool ShouldSerializeWaitSec() => __pbn__WaitSec != null;
            public void ResetWaitSec() => __pbn__WaitSec = null;
            private uint? __pbn__WaitSec;

            [global::ProtoBuf.ProtoMember(2, Name = @"weight")]
            public uint Weight
            {
                get { return __pbn__Weight.GetValueOrDefault(); }
                set { __pbn__Weight = value; }
            }
            public bool ShouldSerializeWeight() => __pbn__Weight != null;
            public void ResetWeight() => __pbn__Weight = null;
            private uint? __pbn__Weight;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosAuthorization : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"threshold")]
            public uint Threshold
            {
                get { return __pbn__Threshold.GetValueOrDefault(); }
                set { __pbn__Threshold = value; }
            }
            public bool ShouldSerializeThreshold() => __pbn__Threshold != null;
            public void ResetThreshold() => __pbn__Threshold = null;
            private uint? __pbn__Threshold;

            [global::ProtoBuf.ProtoMember(2, Name = @"keys")]
            public global::System.Collections.Generic.List<EosTxActionAck.EosAuthorizationKey> Keys { get; } = new global::System.Collections.Generic.List<EosTxActionAck.EosAuthorizationKey>();

            [global::ProtoBuf.ProtoMember(3, Name = @"accounts")]
            public global::System.Collections.Generic.List<EosTxActionAck.EosAuthorizationAccount> Accounts { get; } = new global::System.Collections.Generic.List<EosTxActionAck.EosAuthorizationAccount>();

            [global::ProtoBuf.ProtoMember(4, Name = @"waits")]
            public global::System.Collections.Generic.List<EosTxActionAck.EosAuthorizationWait> Waits { get; } = new global::System.Collections.Generic.List<EosTxActionAck.EosAuthorizationWait>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosActionCommon : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"account")]
            public ulong Account
            {
                get { return __pbn__Account.GetValueOrDefault(); }
                set { __pbn__Account = value; }
            }
            public bool ShouldSerializeAccount() => __pbn__Account != null;
            public void ResetAccount() => __pbn__Account = null;
            private ulong? __pbn__Account;

            [global::ProtoBuf.ProtoMember(2, Name = @"name")]
            public ulong Name
            {
                get { return __pbn__Name.GetValueOrDefault(); }
                set { __pbn__Name = value; }
            }
            public bool ShouldSerializeName() => __pbn__Name != null;
            public void ResetName() => __pbn__Name = null;
            private ulong? __pbn__Name;

            [global::ProtoBuf.ProtoMember(3, Name = @"authorization")]
            public global::System.Collections.Generic.List<EosTxActionAck.EosPermissionLevel> Authorizations { get; } = new global::System.Collections.Generic.List<EosTxActionAck.EosPermissionLevel>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosActionTransfer : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"sender")]
            public ulong Sender
            {
                get { return __pbn__Sender.GetValueOrDefault(); }
                set { __pbn__Sender = value; }
            }
            public bool ShouldSerializeSender() => __pbn__Sender != null;
            public void ResetSender() => __pbn__Sender = null;
            private ulong? __pbn__Sender;

            [global::ProtoBuf.ProtoMember(2, Name = @"receiver")]
            public ulong Receiver
            {
                get { return __pbn__Receiver.GetValueOrDefault(); }
                set { __pbn__Receiver = value; }
            }
            public bool ShouldSerializeReceiver() => __pbn__Receiver != null;
            public void ResetReceiver() => __pbn__Receiver = null;
            private ulong? __pbn__Receiver;

            [global::ProtoBuf.ProtoMember(3, Name = @"quantity")]
            public EosTxActionAck.EosAsset Quantity { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"memo")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Memo
            {
                get { return __pbn__Memo ?? ""; }
                set { __pbn__Memo = value; }
            }
            public bool ShouldSerializeMemo() => __pbn__Memo != null;
            public void ResetMemo() => __pbn__Memo = null;
            private string __pbn__Memo;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosActionDelegate : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"sender")]
            public ulong Sender
            {
                get { return __pbn__Sender.GetValueOrDefault(); }
                set { __pbn__Sender = value; }
            }
            public bool ShouldSerializeSender() => __pbn__Sender != null;
            public void ResetSender() => __pbn__Sender = null;
            private ulong? __pbn__Sender;

            [global::ProtoBuf.ProtoMember(2, Name = @"receiver")]
            public ulong Receiver
            {
                get { return __pbn__Receiver.GetValueOrDefault(); }
                set { __pbn__Receiver = value; }
            }
            public bool ShouldSerializeReceiver() => __pbn__Receiver != null;
            public void ResetReceiver() => __pbn__Receiver = null;
            private ulong? __pbn__Receiver;

            [global::ProtoBuf.ProtoMember(3, Name = @"net_quantity")]
            public EosTxActionAck.EosAsset NetQuantity { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"cpu_quantity")]
            public EosTxActionAck.EosAsset CpuQuantity { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"transfer")]
            public bool Transfer
            {
                get { return __pbn__Transfer.GetValueOrDefault(); }
                set { __pbn__Transfer = value; }
            }
            public bool ShouldSerializeTransfer() => __pbn__Transfer != null;
            public void ResetTransfer() => __pbn__Transfer = null;
            private bool? __pbn__Transfer;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosActionUndelegate : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"sender")]
            public ulong Sender
            {
                get { return __pbn__Sender.GetValueOrDefault(); }
                set { __pbn__Sender = value; }
            }
            public bool ShouldSerializeSender() => __pbn__Sender != null;
            public void ResetSender() => __pbn__Sender = null;
            private ulong? __pbn__Sender;

            [global::ProtoBuf.ProtoMember(2, Name = @"receiver")]
            public ulong Receiver
            {
                get { return __pbn__Receiver.GetValueOrDefault(); }
                set { __pbn__Receiver = value; }
            }
            public bool ShouldSerializeReceiver() => __pbn__Receiver != null;
            public void ResetReceiver() => __pbn__Receiver = null;
            private ulong? __pbn__Receiver;

            [global::ProtoBuf.ProtoMember(3, Name = @"net_quantity")]
            public EosTxActionAck.EosAsset NetQuantity { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"cpu_quantity")]
            public EosTxActionAck.EosAsset CpuQuantity { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosActionRefund : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"owner")]
            public ulong Owner
            {
                get { return __pbn__Owner.GetValueOrDefault(); }
                set { __pbn__Owner = value; }
            }
            public bool ShouldSerializeOwner() => __pbn__Owner != null;
            public void ResetOwner() => __pbn__Owner = null;
            private ulong? __pbn__Owner;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosActionBuyRam : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"payer")]
            public ulong Payer
            {
                get { return __pbn__Payer.GetValueOrDefault(); }
                set { __pbn__Payer = value; }
            }
            public bool ShouldSerializePayer() => __pbn__Payer != null;
            public void ResetPayer() => __pbn__Payer = null;
            private ulong? __pbn__Payer;

            [global::ProtoBuf.ProtoMember(2, Name = @"receiver")]
            public ulong Receiver
            {
                get { return __pbn__Receiver.GetValueOrDefault(); }
                set { __pbn__Receiver = value; }
            }
            public bool ShouldSerializeReceiver() => __pbn__Receiver != null;
            public void ResetReceiver() => __pbn__Receiver = null;
            private ulong? __pbn__Receiver;

            [global::ProtoBuf.ProtoMember(3, Name = @"quantity")]
            public EosTxActionAck.EosAsset Quantity { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosActionBuyRamBytes : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"payer")]
            public ulong Payer
            {
                get { return __pbn__Payer.GetValueOrDefault(); }
                set { __pbn__Payer = value; }
            }
            public bool ShouldSerializePayer() => __pbn__Payer != null;
            public void ResetPayer() => __pbn__Payer = null;
            private ulong? __pbn__Payer;

            [global::ProtoBuf.ProtoMember(2, Name = @"receiver")]
            public ulong Receiver
            {
                get { return __pbn__Receiver.GetValueOrDefault(); }
                set { __pbn__Receiver = value; }
            }
            public bool ShouldSerializeReceiver() => __pbn__Receiver != null;
            public void ResetReceiver() => __pbn__Receiver = null;
            private ulong? __pbn__Receiver;

            [global::ProtoBuf.ProtoMember(3, Name = @"bytes")]
            public uint Bytes
            {
                get { return __pbn__Bytes.GetValueOrDefault(); }
                set { __pbn__Bytes = value; }
            }
            public bool ShouldSerializeBytes() => __pbn__Bytes != null;
            public void ResetBytes() => __pbn__Bytes = null;
            private uint? __pbn__Bytes;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosActionSellRam : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"account")]
            public ulong Account
            {
                get { return __pbn__Account.GetValueOrDefault(); }
                set { __pbn__Account = value; }
            }
            public bool ShouldSerializeAccount() => __pbn__Account != null;
            public void ResetAccount() => __pbn__Account = null;
            private ulong? __pbn__Account;

            [global::ProtoBuf.ProtoMember(2, Name = @"bytes")]
            public ulong Bytes
            {
                get { return __pbn__Bytes.GetValueOrDefault(); }
                set { __pbn__Bytes = value; }
            }
            public bool ShouldSerializeBytes() => __pbn__Bytes != null;
            public void ResetBytes() => __pbn__Bytes = null;
            private ulong? __pbn__Bytes;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosActionVoteProducer : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"voter")]
            public ulong Voter
            {
                get { return __pbn__Voter.GetValueOrDefault(); }
                set { __pbn__Voter = value; }
            }
            public bool ShouldSerializeVoter() => __pbn__Voter != null;
            public void ResetVoter() => __pbn__Voter = null;
            private ulong? __pbn__Voter;

            [global::ProtoBuf.ProtoMember(2, Name = @"proxy")]
            public ulong Proxy
            {
                get { return __pbn__Proxy.GetValueOrDefault(); }
                set { __pbn__Proxy = value; }
            }
            public bool ShouldSerializeProxy() => __pbn__Proxy != null;
            public void ResetProxy() => __pbn__Proxy = null;
            private ulong? __pbn__Proxy;

            [global::ProtoBuf.ProtoMember(3, Name = @"producers")]
            public ulong[] Producers { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosActionUpdateAuth : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"account")]
            public ulong Account
            {
                get { return __pbn__Account.GetValueOrDefault(); }
                set { __pbn__Account = value; }
            }
            public bool ShouldSerializeAccount() => __pbn__Account != null;
            public void ResetAccount() => __pbn__Account = null;
            private ulong? __pbn__Account;

            [global::ProtoBuf.ProtoMember(2, Name = @"permission")]
            public ulong Permission
            {
                get { return __pbn__Permission.GetValueOrDefault(); }
                set { __pbn__Permission = value; }
            }
            public bool ShouldSerializePermission() => __pbn__Permission != null;
            public void ResetPermission() => __pbn__Permission = null;
            private ulong? __pbn__Permission;

            [global::ProtoBuf.ProtoMember(3, Name = @"parent")]
            public ulong Parent
            {
                get { return __pbn__Parent.GetValueOrDefault(); }
                set { __pbn__Parent = value; }
            }
            public bool ShouldSerializeParent() => __pbn__Parent != null;
            public void ResetParent() => __pbn__Parent = null;
            private ulong? __pbn__Parent;

            [global::ProtoBuf.ProtoMember(4, Name = @"auth")]
            public EosTxActionAck.EosAuthorization Auth { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosActionDeleteAuth : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"account")]
            public ulong Account
            {
                get { return __pbn__Account.GetValueOrDefault(); }
                set { __pbn__Account = value; }
            }
            public bool ShouldSerializeAccount() => __pbn__Account != null;
            public void ResetAccount() => __pbn__Account = null;
            private ulong? __pbn__Account;

            [global::ProtoBuf.ProtoMember(2, Name = @"permission")]
            public ulong Permission
            {
                get { return __pbn__Permission.GetValueOrDefault(); }
                set { __pbn__Permission = value; }
            }
            public bool ShouldSerializePermission() => __pbn__Permission != null;
            public void ResetPermission() => __pbn__Permission = null;
            private ulong? __pbn__Permission;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosActionLinkAuth : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"account")]
            public ulong Account
            {
                get { return __pbn__Account.GetValueOrDefault(); }
                set { __pbn__Account = value; }
            }
            public bool ShouldSerializeAccount() => __pbn__Account != null;
            public void ResetAccount() => __pbn__Account = null;
            private ulong? __pbn__Account;

            [global::ProtoBuf.ProtoMember(2, Name = @"code")]
            public ulong Code
            {
                get { return __pbn__Code.GetValueOrDefault(); }
                set { __pbn__Code = value; }
            }
            public bool ShouldSerializeCode() => __pbn__Code != null;
            public void ResetCode() => __pbn__Code = null;
            private ulong? __pbn__Code;

            [global::ProtoBuf.ProtoMember(3, Name = @"type")]
            public ulong Type
            {
                get { return __pbn__Type.GetValueOrDefault(); }
                set { __pbn__Type = value; }
            }
            public bool ShouldSerializeType() => __pbn__Type != null;
            public void ResetType() => __pbn__Type = null;
            private ulong? __pbn__Type;

            [global::ProtoBuf.ProtoMember(4, Name = @"requirement")]
            public ulong Requirement
            {
                get { return __pbn__Requirement.GetValueOrDefault(); }
                set { __pbn__Requirement = value; }
            }
            public bool ShouldSerializeRequirement() => __pbn__Requirement != null;
            public void ResetRequirement() => __pbn__Requirement = null;
            private ulong? __pbn__Requirement;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosActionUnlinkAuth : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"account")]
            public ulong Account
            {
                get { return __pbn__Account.GetValueOrDefault(); }
                set { __pbn__Account = value; }
            }
            public bool ShouldSerializeAccount() => __pbn__Account != null;
            public void ResetAccount() => __pbn__Account = null;
            private ulong? __pbn__Account;

            [global::ProtoBuf.ProtoMember(2, Name = @"code")]
            public ulong Code
            {
                get { return __pbn__Code.GetValueOrDefault(); }
                set { __pbn__Code = value; }
            }
            public bool ShouldSerializeCode() => __pbn__Code != null;
            public void ResetCode() => __pbn__Code = null;
            private ulong? __pbn__Code;

            [global::ProtoBuf.ProtoMember(3, Name = @"type")]
            public ulong Type
            {
                get { return __pbn__Type.GetValueOrDefault(); }
                set { __pbn__Type = value; }
            }
            public bool ShouldSerializeType() => __pbn__Type != null;
            public void ResetType() => __pbn__Type = null;
            private ulong? __pbn__Type;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosActionNewAccount : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"creator")]
            public ulong Creator
            {
                get { return __pbn__Creator.GetValueOrDefault(); }
                set { __pbn__Creator = value; }
            }
            public bool ShouldSerializeCreator() => __pbn__Creator != null;
            public void ResetCreator() => __pbn__Creator = null;
            private ulong? __pbn__Creator;

            [global::ProtoBuf.ProtoMember(2, Name = @"name")]
            public ulong Name
            {
                get { return __pbn__Name.GetValueOrDefault(); }
                set { __pbn__Name = value; }
            }
            public bool ShouldSerializeName() => __pbn__Name != null;
            public void ResetName() => __pbn__Name = null;
            private ulong? __pbn__Name;

            [global::ProtoBuf.ProtoMember(3, Name = @"owner")]
            public EosTxActionAck.EosAuthorization Owner { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"active")]
            public EosTxActionAck.EosAuthorization Active { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EosActionUnknown : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"data_size")]
            public uint DataSize
            {
                get { return __pbn__DataSize.GetValueOrDefault(); }
                set { __pbn__DataSize = value; }
            }
            public bool ShouldSerializeDataSize() => __pbn__DataSize != null;
            public void ResetDataSize() => __pbn__DataSize = null;
            private uint? __pbn__DataSize;

            [global::ProtoBuf.ProtoMember(2, Name = @"data_chunk")]
            public byte[] DataChunk
            {
                get { return __pbn__DataChunk; }
                set { __pbn__DataChunk = value; }
            }
            public bool ShouldSerializeDataChunk() => __pbn__DataChunk != null;
            public void ResetDataChunk() => __pbn__DataChunk = null;
            private byte[] __pbn__DataChunk;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EosSignedTx : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"signature_v")]
        public uint SignatureV
        {
            get { return __pbn__SignatureV.GetValueOrDefault(); }
            set { __pbn__SignatureV = value; }
        }
        public bool ShouldSerializeSignatureV() => __pbn__SignatureV != null;
        public void ResetSignatureV() => __pbn__SignatureV = null;
        private uint? __pbn__SignatureV;

        [global::ProtoBuf.ProtoMember(2, Name = @"signature_r")]
        public byte[] SignatureR
        {
            get { return __pbn__SignatureR; }
            set { __pbn__SignatureR = value; }
        }
        public bool ShouldSerializeSignatureR() => __pbn__SignatureR != null;
        public void ResetSignatureR() => __pbn__SignatureR = null;
        private byte[] __pbn__SignatureR;

        [global::ProtoBuf.ProtoMember(3, Name = @"signature_s")]
        public byte[] SignatureS
        {
            get { return __pbn__SignatureS; }
            set { __pbn__SignatureS = value; }
        }
        public bool ShouldSerializeSignatureS() => __pbn__SignatureS != null;
        public void ResetSignatureS() => __pbn__SignatureS = null;
        private byte[] __pbn__SignatureS;

    }

}

#pragma warning restore
