// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: messages-cardano.proto

#pragma warning disable
using Trezor.Net.Contracts.Common;

namespace Trezor.Net.Contracts.Cardano
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CardanoGetAddress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"show_display")]
        public bool ShowDisplay
        {
            get { return __pbn__ShowDisplay.GetValueOrDefault(); }
            set { __pbn__ShowDisplay = value; }
        }
        public bool ShouldSerializeShowDisplay() => __pbn__ShowDisplay != null;
        public void ResetShowDisplay() => __pbn__ShowDisplay = null;
        private bool? __pbn__ShowDisplay;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CardanoAddress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address
        {
            get { return __pbn__Address ?? ""; }
            set { __pbn__Address = value; }
        }
        public bool ShouldSerializeAddress() => __pbn__Address != null;
        public void ResetAddress() => __pbn__Address = null;
        private string __pbn__Address;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CardanoGetPublicKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
        public uint[] AddressNs { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"show_display")]
        public bool ShowDisplay
        {
            get { return __pbn__ShowDisplay.GetValueOrDefault(); }
            set { __pbn__ShowDisplay = value; }
        }
        public bool ShouldSerializeShowDisplay() => __pbn__ShowDisplay != null;
        public void ResetShowDisplay() => __pbn__ShowDisplay = null;
        private bool? __pbn__ShowDisplay;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CardanoPublicKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"xpub")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Xpub
        {
            get { return __pbn__Xpub ?? ""; }
            set { __pbn__Xpub = value; }
        }
        public bool ShouldSerializeXpub() => __pbn__Xpub != null;
        public void ResetXpub() => __pbn__Xpub = null;
        private string __pbn__Xpub;

        [global::ProtoBuf.ProtoMember(2, Name = @"node")]
        public HDNodeType Node { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CardanoSignTx : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"inputs")]
        public global::System.Collections.Generic.List<CardanoTxInputType> Inputs { get; } = new global::System.Collections.Generic.List<CardanoTxInputType>();

        [global::ProtoBuf.ProtoMember(2, Name = @"outputs")]
        public global::System.Collections.Generic.List<CardanoTxOutputType> Outputs { get; } = new global::System.Collections.Generic.List<CardanoTxOutputType>();

        [global::ProtoBuf.ProtoMember(3, Name = @"transactions_count")]
        public uint TransactionsCount
        {
            get { return __pbn__TransactionsCount.GetValueOrDefault(); }
            set { __pbn__TransactionsCount = value; }
        }
        public bool ShouldSerializeTransactionsCount() => __pbn__TransactionsCount != null;
        public void ResetTransactionsCount() => __pbn__TransactionsCount = null;
        private uint? __pbn__TransactionsCount;

        [global::ProtoBuf.ProtoMember(5, Name = @"protocol_magic")]
        public uint ProtocolMagic
        {
            get { return __pbn__ProtocolMagic.GetValueOrDefault(); }
            set { __pbn__ProtocolMagic = value; }
        }
        public bool ShouldSerializeProtocolMagic() => __pbn__ProtocolMagic != null;
        public void ResetProtocolMagic() => __pbn__ProtocolMagic = null;
        private uint? __pbn__ProtocolMagic;

        [global::ProtoBuf.ProtoContract()]
        public partial class CardanoTxInputType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"address_n")]
            public uint[] AddressNs { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"prev_hash")]
            public byte[] PrevHash
            {
                get { return __pbn__PrevHash; }
                set { __pbn__PrevHash = value; }
            }
            public bool ShouldSerializePrevHash() => __pbn__PrevHash != null;
            public void ResetPrevHash() => __pbn__PrevHash = null;
            private byte[] __pbn__PrevHash;

            [global::ProtoBuf.ProtoMember(3, Name = @"prev_index")]
            public uint PrevIndex
            {
                get { return __pbn__PrevIndex.GetValueOrDefault(); }
                set { __pbn__PrevIndex = value; }
            }
            public bool ShouldSerializePrevIndex() => __pbn__PrevIndex != null;
            public void ResetPrevIndex() => __pbn__PrevIndex = null;
            private uint? __pbn__PrevIndex;

            [global::ProtoBuf.ProtoMember(4, Name = @"type")]
            public uint Type
            {
                get { return __pbn__Type.GetValueOrDefault(); }
                set { __pbn__Type = value; }
            }
            public bool ShouldSerializeType() => __pbn__Type != null;
            public void ResetType() => __pbn__Type = null;
            private uint? __pbn__Type;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class CardanoTxOutputType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"address")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Address
            {
                get { return __pbn__Address ?? ""; }
                set { __pbn__Address = value; }
            }
            public bool ShouldSerializeAddress() => __pbn__Address != null;
            public void ResetAddress() => __pbn__Address = null;
            private string __pbn__Address;

            [global::ProtoBuf.ProtoMember(2, Name = @"address_n")]
            public uint[] AddressNs { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"amount")]
            public ulong Amount
            {
                get { return __pbn__Amount.GetValueOrDefault(); }
                set { __pbn__Amount = value; }
            }
            public bool ShouldSerializeAmount() => __pbn__Amount != null;
            public void ResetAmount() => __pbn__Amount = null;
            private ulong? __pbn__Amount;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CardanoTxRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tx_index")]
        public uint TxIndex
        {
            get { return __pbn__TxIndex.GetValueOrDefault(); }
            set { __pbn__TxIndex = value; }
        }
        public bool ShouldSerializeTxIndex() => __pbn__TxIndex != null;
        public void ResetTxIndex() => __pbn__TxIndex = null;
        private uint? __pbn__TxIndex;

        [global::ProtoBuf.ProtoMember(2, Name = @"tx_hash")]
        public byte[] TxHash
        {
            get { return __pbn__TxHash; }
            set { __pbn__TxHash = value; }
        }
        public bool ShouldSerializeTxHash() => __pbn__TxHash != null;
        public void ResetTxHash() => __pbn__TxHash = null;
        private byte[] __pbn__TxHash;

        [global::ProtoBuf.ProtoMember(3, Name = @"tx_body")]
        public byte[] TxBody
        {
            get { return __pbn__TxBody; }
            set { __pbn__TxBody = value; }
        }
        public bool ShouldSerializeTxBody() => __pbn__TxBody != null;
        public void ResetTxBody() => __pbn__TxBody = null;
        private byte[] __pbn__TxBody;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CardanoTxAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"transaction")]
        public byte[] Transaction
        {
            get { return __pbn__Transaction; }
            set { __pbn__Transaction = value; }
        }
        public bool ShouldSerializeTransaction() => __pbn__Transaction != null;
        public void ResetTransaction() => __pbn__Transaction = null;
        private byte[] __pbn__Transaction;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CardanoSignedTx : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tx_hash")]
        public byte[] TxHash
        {
            get { return __pbn__TxHash; }
            set { __pbn__TxHash = value; }
        }
        public bool ShouldSerializeTxHash() => __pbn__TxHash != null;
        public void ResetTxHash() => __pbn__TxHash = null;
        private byte[] __pbn__TxHash;

        [global::ProtoBuf.ProtoMember(2, Name = @"tx_body")]
        public byte[] TxBody
        {
            get { return __pbn__TxBody; }
            set { __pbn__TxBody = value; }
        }
        public bool ShouldSerializeTxBody() => __pbn__TxBody != null;
        public void ResetTxBody() => __pbn__TxBody = null;
        private byte[] __pbn__TxBody;

    }

}

#pragma warning restore
